const money=n=>"₹"+n.toLocaleString("en-IN");
function cart(){return JSON.parse(localStorage.getItem("psmart-cart")||"[]")}
function saveCart(c){localStorage.setItem("psmart-cart",JSON.stringify(c));updateCount()}
function updateCount(){let n=cart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("#count").forEach(e=>e.textContent=n)}
function add(id){let c=cart(),x=c.find(a=>a.id==id);x?x.qty++:c.push({id:+id,qty:1});saveCart(c);alert("Added to cart ✓")}
function remove(id){saveCart(cart().filter(x=>x.id!=id));renderCart()}
function search(){let q=document.querySelector("#search").value.trim();if(q)location.href="products.html?q="+encodeURIComponent(q)}
function card(p){return `<article class="product"><a href="product.html?id=${p.id}"><div class="pic">${p.icon}</div></a><small>${p.brand}</small><h3>${p.name}</h3><div class="rating">★ ${p.rating}</div><b>${money(p.price)}</b> <del>${money(p.old)}</del><button onclick="add(${p.id})">🛒 Add to Cart</button></article>`}
function renderProducts(){let el=document.querySelector("#products");if(!el)return;let u=new URLSearchParams(location.search),cat=u.get("cat"),q=(u.get("q")||"").toLowerCase();let a=PRODUCTS.filter(p=>(!cat||p.cat==cat)&&(!q||(p.name+" "+p.brand+" "+p.cat).toLowerCase().includes(q)));let s=document.querySelector("#sort")?.value;if(s=="low")a.sort((x,y)=>x.price-y.price);if(s=="high")a.sort((x,y)=>y.price-x.price);document.querySelector("#title").textContent=cat?cat+" Products":q?`Search: ${q}`:"All Products";el.innerHTML=a.map(card).join("")||"<div class='empty'>No products found.</div>"}
function renderHome(){let e=document.querySelector("#homeProducts");if(e)e.innerHTML=PRODUCTS.slice(0,5).map(card).join("")}
function detail(){let e=document.querySelector("#detail");if(!e)return;let p=PRODUCTS.find(x=>x.id==new URLSearchParams(location.search).get("id"))||PRODUCTS[0];e.innerHTML=`<div class="bigpic">${p.icon}</div><div><small>${p.brand}</small><h1>${p.name}</h1><div class="rating">★ ${p.rating} / 5</div><h2>${money(p.price)} <del>${money(p.old)}</del></h2><p class="green">✓ Available &nbsp; ✓ Secure Payment &nbsp; ✓ Easy Returns</p><p>Premium quality product with fast delivery and customer support from PS Mart.</p><button class="goldbtn" onclick="add(${p.id})">🛒 Add to Cart</button> <a class="buy" href="cart.html">Buy Now</a><hr><h3>Description</h3><p>Product details, specifications and customer reviews will appear here.</p></div>`}
function renderCart(){let e=document.querySelector("#cart");if(!e)return;let c=cart();if(!c.length){e.innerHTML="<div class='empty'>Your cart is empty 🛒<br><a href='products.html'>Continue Shopping</a></div>";return}let total=0;e.innerHTML=`<div>${c.map(x=>{let p=PRODUCTS.find(a=>a.id==x.id);total+=p.price*x.qty;return `<div class="cartrow"><span class="pic mini">${p.icon}</span><div><b>${p.name}</b><p>${money(p.price)} × ${x.qty}</p></div><button onclick="remove(${p.id})">Remove</button></div>`}).join("")}</div><div class="summary"><h2>Price Details</h2><p>Total <b>${money(total)}</b></p><p>Delivery <b class="green">FREE</b></p><hr><h2>${money(total)}</h2><a class="goldbtn block" href="checkout.html">Proceed to Checkout →</a></div>`}
function summary(){let e=document.querySelector("#summary");if(!e)return;let total=cart().reduce((s,x)=>s+(PRODUCTS.find(p=>p.id==x.id)?.price||0)*x.qty,0);e.innerHTML=`<h2>Order Summary</h2><p>Items: ${cart().reduce((s,x)=>s+x.qty,0)}</p><h2>Total: ${money(total)}</h2><button class="goldbtn block" onclick="alert('Demo order placed. Real payment/order system will be connected in Part 2.')">Place Order</button>`}
updateCount();renderHome();renderProducts();detail();renderCart();summary();