javascript
/* =====================================================
   PS MART - MULTI LANGUAGE TRANSLATION SYSTEM
   20 LANGUAGES
===================================================== */

const PS_TRANSLATIONS = {

  Hindi: {
    "Search for Products, Brands and More":"Products, Brands aur More search karein",
    "👤 Login":"👤 Login",
    "Sell on PS Mart":"PS Mart par Sell karein",
    "🛒 Cart":"🛒 Cart",
    "Delivery location":"Delivery location",
    "Select your location →":"Apni location select karein →",
    "For You":"Aapke Liye",
    "Mobiles":"Mobiles",
    "Fashion":"Fashion",
    "Electronics":"Electronics",
    "Beauty":"Beauty",
    "Home":"Home",
    "Grocery":"Grocery",
    "Accessories":"Accessories",
    "PS MART EXCLUSIVE":"PS MART EXCLUSIVE",
    "Big Deals":"Bade Offers",
    "Every Day":"Har Din",
    "Shop Now →":"Abhi Shop Karein →",
    "OFF":"OFF",
    "Electronics Sale":"Electronics Sale",
    "Best deals on gadgets":"Gadgets par best deals",
    "Fashion Deals":"Fashion Deals",
    "Style at better prices":"Behtar prices par style",
    "Home Essentials":"Home Essentials",
    "Upgrade your home":"Apne home ko upgrade karein",
    "Best Deals For You 🔥":"Aapke Liye Best Deals 🔥",
    "View All →":"Sabhi Dekhein →",
    "Fast Delivery":"Fast Delivery",
    "Reliable delivery":"Reliable delivery",
    "Secure Payment":"Secure Payment",
    "Safe checkout":"Safe checkout",
    "Easy Returns":"Easy Returns",
    "Simple returns":"Simple returns",
    "Customer Support":"Customer Support",
    "Help when needed":"Zarurat par Help",
    "All Products":"Sabhi Products",
    "Wishlist":"Wishlist",
    "Customer":"Customer",
    "My Account":"Mera Account",
    "My Orders":"Mere Orders",
    "My Cart":"Mera Cart",
    "Seller":"Seller",
    "Seller Dashboard":"Seller Dashboard",
    "Support":"Support",
    "About Us":"Hamare Baare Mein",
    "Privacy":"Privacy",
    "Terms":"Terms",
    "Contact":"Contact",
    "Categories":"Categories",
    "Account":"Account"
  },

  Bengali: {
    "Search for Products, Brands and More":"পণ্য, ব্র্যান্ড এবং আরও কিছু খুঁজুন",
    "👤 Login":"👤 লগইন",
    "Sell on PS Mart":"PS Mart-এ বিক্রি করুন",
    "🛒 Cart":"🛒 কার্ট",
    "Delivery location":"ডেলিভারি ঠিকানা",
    "Select your location →":"আপনার অবস্থান নির্বাচন করুন →",
    "For You":"আপনার জন্য",
    "Mobiles":"মোবাইল",
    "Fashion":"ফ্যাশন",
    "Electronics":"ইলেকট্রনিক্স",
    "Beauty":"বিউটি",
    "Home":"হোম",
    "Grocery":"মুদি",
    "Accessories":"অ্যাক্সেসরিজ",
    "PS MART EXCLUSIVE":"PS MART বিশেষ",
    "Big Deals":"বড় অফার",
    "Every Day":"প্রতিদিন",
    "Shop Now →":"এখনই কিনুন →",
    "OFF":"ছাড়",
    "Electronics Sale":"ইলেকট্রনিক্স সেল",
    "Best deals on gadgets":"গ্যাজেটে সেরা অফার",
    "Fashion Deals":"ফ্যাশন অফার",
    "Style at better prices":"ভালো দামে স্টাইল",
    "Home Essentials":"হোম প্রয়োজনীয় জিনিস",
    "Upgrade your home":"আপনার বাড়ি সাজান",
    "Best Deals For You 🔥":"আপনার জন্য সেরা অফার 🔥",
    "View All →":"সব দেখুন →",
    "Fast Delivery":"দ্রুত ডেলিভারি",
    "Reliable delivery":"নির্ভরযোগ্য ডেলিভারি",
    "Secure Payment":"নিরাপদ পেমেন্ট",
    "Safe checkout":"নিরাপদ চেকআউট",
    "Easy Returns":"সহজ রিটার্ন",
    "Simple returns":"সহজ রিটার্ন ব্যবস্থা",
    "Customer Support":"কাস্টমার সাপোর্ট",
    "Help when needed":"প্রয়োজনে সাহায্য",
    "All Products":"সব পণ্য",
    "Wishlist":"উইশলিস্ট",
    "Customer":"গ্রাহক",
    "My Account":"আমার অ্যাকাউন্ট",
    "My Orders":"আমার অর্ডার",
    "My Cart":"আমার কার্ট",
    "Seller":"বিক্রেতা",
    "Seller Dashboard":"বিক্রেতা ড্যাশবোর্ড",
    "Support":"সহায়তা",
    "About Us":"আমাদের সম্পর্কে",
    "Privacy":"গোপনীয়তা",
    "Terms":"শর্তাবলী",
    "Contact":"যোগাযোগ",
    "Categories":"ক্যাটাগরি",
    "Account":"অ্যাকাউন্ট"
  },

  Marathi: {
    "Search for Products, Brands and More":"उत्पादने, ब्रँड आणि अधिक शोधा",
    "👤 Login":"👤 लॉगिन",
    "Sell on PS Mart":"PS Mart वर विक्री करा",
    "🛒 Cart":"🛒 कार्ट",
    "Delivery location":"डिलिव्हरी ठिकाण",
    "Select your location →":"तुमचे ठिकाण निवडा →",
    "For You":"तुमच्यासाठी",
    "Mobiles":"मोबाईल",
    "Fashion":"फॅशन",
    "Electronics":"इलेक्ट्रॉनिक्स",
    "Beauty":"ब्युटी",
    "Home":"होम",
    "Grocery":"किराणा",
    "Accessories":"अॅक्सेसरीज",
    "PS MART EXCLUSIVE":"PS MART खास",
    "Big Deals":"मोठ्या ऑफर्स",
    "Every Day":"दररोज",
    "Shop Now →":"आता खरेदी करा →",
    "OFF":"सूट",
    "Electronics Sale":"इलेक्ट्रॉनिक्स सेल",
    "Best deals on gadgets":"गॅजेट्सवर सर्वोत्तम ऑफर्स",
    "Fashion Deals":"फॅशन ऑफर्स",
    "Style at better prices":"चांगल्या किमतीत स्टाइल",
    "Home Essentials":"घरासाठी आवश्यक वस्तू",
    "Upgrade your home":"तुमचे घर अपग्रेड करा",
    "Best Deals For You 🔥":"तुमच्यासाठी सर्वोत्तम ऑफर्स 🔥",
    "View All →":"सर्व पहा →",
    "Fast Delivery":"जलद डिलिव्हरी",
    "Reliable delivery":"विश्वसनीय डिलिव्हरी",
    "Secure Payment":"सुरक्षित पेमेंट",
    "Safe checkout":"सुरक्षित चेकआउट",
    "Easy Returns":"सोपे रिटर्न",
    "Simple returns":"सोपे रिटर्न",
    "Customer Support":"ग्राहक सेवा",
    "Help when needed":"गरजेनुसार मदत",
    "All Products":"सर्व उत्पादने",
    "Wishlist":"विशलिस्ट",
    "Customer":"ग्राहक",
    "My Account":"माझे खाते",
    "My Orders":"माझे ऑर्डर",
    "My Cart":"माझी कार्ट",
    "Seller":"विक्रेता",
    "Seller Dashboard":"विक्रेता डॅशबोर्ड",
    "Support":"मदत",
    "About Us":"आमच्याबद्दल",
    "Privacy":"गोपनीयता",
    "Terms":"अटी",
    "Contact":"संपर्क",
    "Categories":"श्रेणी",
    "Account":"खाते"
  },

  Telugu: {
    "Search for Products, Brands and More":"ఉత్పత్తులు, బ్రాండ్లు మరియు మరిన్ని శోధించండి",
    "👤 Login":"👤 లాగిన్",
    "Sell on PS Mart":"PS Martలో అమ్మండి",
    "🛒 Cart":"🛒 కార్ట్",
    "Delivery location":"డెలివరీ స్థానం",
    "Select your location →":"మీ స్థానాన్ని ఎంచుకోండి →",
    "For You":"మీ కోసం",
    "Mobiles":"మొబైల్స్",
    "Fashion":"ఫ్యాషన్",
    "Electronics":"ఎలక్ట్రానిక్స్",
    "Beauty":"బ్యూటీ",
    "Home":"హోమ్",
    "Grocery":"కిరాణా",
    "Accessories":"యాక్సెసరీస్",
    "PS MART EXCLUSIVE":"PS MART ప్రత్యేకం",
    "Big Deals":"పెద్ద ఆఫర్లు",
    "Every Day":"ప్రతిరోజూ",
    "Shop Now →":"ఇప్పుడే కొనండి →",
    "OFF":"తగ్గింపు",
    "Electronics Sale":"ఎలక్ట్రానిక్స్ సేల్",
    "Best deals on gadgets":"గాడ్జెట్లపై ఉత్తమ ఆఫర్లు",
    "Fashion Deals":"ఫ్యాషన్ ఆఫర్లు",
    "Style at better prices":"మంచి ధరల్లో స్టైల్",
    "Home Essentials":"ఇంటి అవసరాలు",
    "Upgrade your home":"మీ ఇంటిని అప్‌గ్రేడ్ చేయండి",
    "Best Deals For You 🔥":"మీ కోసం ఉత్తమ ఆఫర్లు 🔥",
    "View All →":"అన్నీ చూడండి →",
    "Fast Delivery":"వేగవంతమైన డెలివరీ",
    "Reliable delivery":"నమ్మకమైన డెలివరీ",
    "Secure Payment":"సురక్షిత చెల్లింపు",
    "Safe checkout":"సురక్షిత చెక్అవుట్",
    "Easy Returns":"సులభమైన రిటర్న్స్",
    "Simple returns":"సులభమైన రిటర్న్స్",
    "Customer Support":"కస్టమర్ సపోర్ట్",
    "Help when needed":"అవసరమైనప్పుడు సహాయం",
    "All Products":"అన్ని ఉత్పత్తులు",
    "Wishlist":"విష్‌లిస్ట్",
    "Customer":"కస్టమర్",
    "My Account":"నా ఖాతా",
    "My Orders":"నా ఆర్డర్లు",
    "My Cart":"నా కార్ట్",
    "Seller":"విక్రేత",
    "Seller Dashboard":"విక్రేత డ్యాష్‌బోర్డ్",
    "Support":"సహాయం",
    "About Us":"మా గురించి",
    "Privacy":"గోప్యత",
    "Terms":"నిబంధనలు",
    "Contact":"సంప్రదించండి",
    "Categories":"కేటగిరీలు",
    "Account":"ఖాతా"
  },

  Tamil: {
    "Search for Products, Brands and More":"பொருட்கள், பிராண்டுகள் மற்றும் பலவற்றைத் தேடுங்கள்",
    "👤 Login":"👤 உள்நுழைவு",
    "Sell on PS Mart":"PS Mart-ல் விற்கவும்",
    "🛒 Cart":"🛒 கார்ட்",
    "Delivery location":"டெலிவரி இடம்",
    "Select your location →":"உங்கள் இடத்தைத் தேர்ந்தெடுக்கவும் →",
    "For You":"உங்களுக்காக",
    "Mobiles":"மொபைல்கள்",
    "Fashion":"ஃபேஷன்",
    "Electronics":"எலக்ட்ரானிக்ஸ்",
    "Beauty":"அழகு",
    "Home":"வீடு",
    "Grocery":"மளிகை",
    "Accessories":"அணிகலன்கள்",
    "PS MART EXCLUSIVE":"PS MART சிறப்பு",
    "Big Deals":"பெரிய சலுகைகள்",
    "Every Day":"தினமும்",
    "Shop Now →":"இப்போது வாங்குங்கள் →",
    "OFF":"தள்ளுபடி",
    "Electronics Sale":"எலக்ட்ரானிக்ஸ் விற்பனை",
    "Best deals on gadgets":"கேஜெட்களுக்கு சிறந்த சலுகைகள்",
    "Fashion Deals":"ஃபேஷன் சலுகைகள்",
    "Style at better prices":"சிறந்த விலையில் ஸ்டைல்",
    "Home Essentials":"வீட்டு அத்தியாவசியங்கள்",
    "Upgrade your home":"உங்கள் வீட்டை மேம்படுத்துங்கள்",
    "Best Deals For You 🔥":"உங்களுக்கான சிறந்த சலுகைகள் 🔥",
    "View All →":"அனைத்தையும் பார்க்கவும் →",
    "Fast Delivery":"வேகமான டெலிவரி",
    "Reliable delivery":"நம்பகமான டெலிவரி",
    "Secure Payment":"பாதுகாப்பான பணம் செலுத்துதல்",
    "Safe checkout":"பாதுகாப்பான செக்அவுட்",
    "Easy Returns":"எளிதான ரிட்டர்ன்ஸ்",
    "Simple returns":"எளிய ரிட்டர்ன்ஸ்",
    "Customer Support":"வாடிக்கையாளர் ஆதரவு",
    "Help when needed":"தேவைப்படும் போது உதவி",
    "All Products":"அனைத்து பொருட்கள்",
    "Wishlist":"விருப்பப்பட்டியல்",
    "Customer":"வாடிக்கையாளர்",
    "My Account":"எனது கணக்கு",
    "My Orders":"எனது ஆர்டர்கள்",
    "My Cart":"எனது கார்ட்",
    "Seller":"விற்பனையாளர்",
    "Seller Dashboard":"விற்பனையாளர் டாஷ்போர்டு",
    "Support":"ஆதரவு",
    "About Us":"எங்களைப் பற்றி",
    "Privacy":"தனியுரிமை",
    "Terms":"விதிமுறைகள்",
    "Contact":"தொடர்பு",
    "Categories":"வகைகள்",
    "Account":"கணக்கு"
  },

  Gujarati: {
    "Search for Products, Brands and More":"પ્રોડક્ટ્સ, બ્રાન્ડ્સ અને વધુ શોધો",
    "👤 Login":"👤 લોગિન",
    "Sell on PS Mart":"PS Mart પર વેચો",
    "🛒 Cart":"🛒 કાર્ટ",
    "Delivery location":"ડિલિવરી સ્થાન",
    "Select your location →":"તમારું સ્થાન પસંદ કરો →",
    "For You":"તમારા માટે",
    "Mobiles":"મોબાઇલ",
    "Fashion":"ફેશન",
    "Electronics":"ઇલેક્ટ્રોનિક્સ",
    "Beauty":"બ્યુટી",
    "Home":"હોમ",
    "Grocery":"કિરાણા",
    "Accessories":"એસેસરીઝ",
    "PS MART EXCLUSIVE":"PS MART ખાસ",
    "Big Deals":"મોટી ઑફર્સ",
    "Every Day":"દરરોજ",
    "Shop Now →":"હમણાં ખરીદો →",
    "OFF":"છૂટ",
    "Electronics Sale":"ઇલેક્ટ્રોનિક્સ સેલ",
    "Best deals on gadgets":"ગેજેટ્સ પર શ્રેષ્ઠ ઑફર્સ",
    "Fashion Deals":"ફેશન ઑફર્સ",
    "Style at better prices":"સારા ભાવે સ્ટાઇલ",
    "Home Essentials":"ઘરની જરૂરી વસ્તુઓ",
    "Upgrade your home":"તમારું ઘર અપગ્રેડ કરો",
    "Best Deals For You 🔥":"તમારા માટે શ્રેષ્ઠ ઑફર્સ 🔥",
    "View All →":"બધું જુઓ →",
    "Fast Delivery":"ઝડપી ડિલિવરી",
    "Reliable delivery":"વિશ્વસનીય ડિલિવરી",
    "Secure Payment":"સુરક્ષિત ચુકવણી",
    "Safe checkout":"સુરક્ષિત ચેકઆઉટ",
    "Easy Returns":"સરળ રિટર્ન",
    "Simple returns":"સરળ રિટર્ન",
    "Customer Support":"ગ્રાહક સેવા",
    "Help when needed":"જરૂર પડે ત્યારે મદદ",
    "All Products":"બધા પ્રોડક્ટ્સ",
    "Wishlist":"વિશલિસ્ટ",
    "Customer":"ગ્રાહક",
    "My Account":"મારું એકાઉન્ટ",
    "My Orders":"મારા ઓર્ડર્સ",
    "My Cart":"મારી કાર્ટ",
    "Seller":"વિક્રેતા",
    "Seller Dashboard":"વિક્રેતા ડેશબોર્ડ",
    "Support":"મદદ",
    "About Us":"અમારા વિશે",
    "Privacy":"ગોપનીયતા",
    "Terms":"નિયમો",
    "Contact":"સંપર્ક",
    "Categories":"કેટેગરીઝ",
    "Account":"એકાઉન્ટ"
  },

  Kannada: {
    "Search for Products, Brands and More":"ಉತ್ಪನ್ನಗಳು, ಬ್ರ್ಯಾಂಡ್‌ಗಳು ಮತ್ತು ಹೆಚ್ಚಿನದನ್ನು ಹುಡುಕಿ",
    "👤 Login":"👤 ಲಾಗಿನ್",
    "Sell on PS Mart":"PS Mart ನಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ",
    "🛒 Cart":"🛒 ಕಾರ್ಟ್",
    "Delivery location":"ವಿತರಣಾ ಸ್ಥಳ",
    "Select your location →":"ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ →",
    "For You":"ನಿಮಗಾಗಿ",
    "Mobiles":"ಮೊಬೈಲ್‌ಗಳು",
    "Fashion":"ಫ್ಯಾಷನ್",
    "Electronics":"ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್",
    "Beauty":"ಬ್ಯೂಟಿ",
    "Home":"ಮನೆ",
    "Grocery":"ದಿನಸಿ",
    "Accessories":"ಆಕ್ಸೆಸರೀಸ್",
    "PS MART EXCLUSIVE":"PS MART ವಿಶೇಷ",
    "Big Deals":"ದೊಡ್ಡ ಆಫರ್‌ಗಳು",
    "Every Day":"ಪ್ರತಿದಿನ",
    "Shop Now →":"ಈಗ ಖರೀದಿಸಿ →",
    "OFF":"ರಿಯಾಯಿತಿ",
    "Electronics Sale":"ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಸೇಲ್",
    "Best deals on gadgets":"ಗ್ಯಾಜೆಟ್‌ಗಳ ಮೇಲೆ ಉತ್ತಮ ಆಫರ್‌ಗಳು",
    "Fashion Deals":"ಫ್ಯಾಷನ್ ಆಫರ್‌ಗಳು",
    "Style at better prices":"ಉತ್ತಮ ಬೆಲೆಯಲ್ಲಿ ಸ್ಟೈಲ್",
    "Home Essentials":"ಮನೆಯ ಅಗತ್ಯ ವಸ್ತುಗಳು",
    "Upgrade your home":"ನಿಮ್ಮ ಮನೆಯನ್ನು ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    "Best Deals For You 🔥":"ನಿಮಗಾಗಿ ಉತ್ತಮ ಆಫರ್‌ಗಳು 🔥",
    "View All →":"ಎಲ್ಲವನ್ನೂ ನೋಡಿ →",
    "Fast Delivery":"ವೇಗದ ಡೆಲಿವರಿ",
    "Reliable delivery":"ವಿಶ್ವಾಸಾರ್ಹ ಡೆಲಿವರಿ",
    "Secure Payment":"ಸುರಕ್ಷಿತ ಪಾವತಿ",
    "Safe checkout":"ಸುರಕ್ಷಿತ ಚೆಕ್‌ಔಟ್",
    "Easy Returns":"ಸುಲಭ ರಿಟರ್ನ್ಸ್",
    "Simple returns":"ಸರಳ ರಿಟರ್ನ್ಸ್",
    "Customer Support":"ಗ್ರಾಹಕ ಸಹಾಯ",
    "Help when needed":"ಅಗತ್ಯವಿದ್ದಾಗ ಸಹಾಯ",
    "All Products":"ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು",
    "Wishlist":"ವಿಶ್‌ಲಿಸ್ಟ್",
    "Customer":"ಗ್ರಾಹಕ",
    "My Account":"ನನ್ನ ಖಾತೆ",
    "My Orders":"ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    "My Cart":"ನನ್ನ ಕಾರ್ಟ್",
    "Seller":"ಮಾರಾಟಗಾರ",
    "Seller Dashboard":"ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Support":"ಸಹಾಯ",
    "About Us":"ನಮ್ಮ ಬಗ್ಗೆ",
    "Privacy":"ಗೌಪ್ಯತೆ",
    "Terms":"ನಿಯಮಗಳು",
    "Contact":"ಸಂಪರ್ಕ",
    "Categories":"ವರ್ಗಗಳು",
    "Account":"ಖಾತೆ"
  },

  Malayalam: {
    "Search for Products, Brands and More":"ഉൽപ്പന്നങ്ങൾ, ബ്രാൻഡുകൾ എന്നിവ തിരയുക",
    "👤 Login":"👤 ലോഗിൻ",
    "Sell on PS Mart":"PS Mart-ൽ വിൽക്കുക",
    "🛒 Cart":"🛒 കാർട്ട്",
    "Delivery location":"ഡെലിവറി സ്ഥലം",
    "Select your location →":"നിങ്ങളുടെ സ്ഥലം തിരഞ്ഞെടുക്കുക →",
    "For You":"നിങ്ങൾക്കായി",
    "Mobiles":"മൊബൈലുകൾ",
    "Fashion":"ഫാഷൻ",
    "Electronics":"ഇലക്ട്രോണിക്സ്",
    "Beauty":"ബ്യൂട്ടി",
    "Home":"ഹോം",
    "Grocery":"പലചരക്ക്",
    "Accessories":"ആക്സസറീസ്",
    "PS MART EXCLUSIVE":"PS MART പ്രത്യേക",
    "Big Deals":"വലിയ ഓഫറുകൾ",
    "Every Day":"എല്ലാ ദിവസവും",
    "Shop Now →":"ഇപ്പോൾ വാങ്ങുക →",
    "OFF":"ഇളവ്",
    "Electronics Sale":"ഇലക്ട്രോണിക്സ് സെയിൽ",
    "Best deals on gadgets":"ഗാഡ്ജറ്റുകളിൽ മികച്ച ഓഫറുകൾ",
    "Fashion Deals":"ഫാഷൻ ഓഫറുകൾ",
    "Style at better prices":"മികച്ച വിലയിൽ സ്റ്റൈൽ",
    "Home Essentials":"വീട്ടാവശ്യങ്ങൾ",
    "Upgrade your home":"നിങ്ങളുടെ വീട് മെച്ചപ്പെടുത്തുക",
    "Best Deals For You 🔥":"നിങ്ങൾക്കായുള്ള മികച്ച ഓഫറുകൾ 🔥",
    "View All →":"എല്ലാം കാണുക →",
    "Fast Delivery":"വേഗത്തിലുള്ള ഡെലിവറി",
    "Reliable delivery":"വിശ്വസനീയമായ ഡെലിവറി",
    "Secure Payment":"സുരക്ഷിത പേയ്മെന്റ്",
    "Safe checkout":"സുരക്ഷിത ചെക്ക്ഔട്ട്",
    "Easy Returns":"എളുപ്പമുള്ള റിട്ടേൺ",
    "Simple returns":"ലളിതമായ റിട്ടേൺ",
    "Customer Support":"കസ്റ്റമർ സപ്പോർട്ട്",
    "Help when needed":"ആവശ്യമായപ്പോൾ സഹായം",
    "All Products":"എല്ലാ ഉൽപ്പന്നങ്ങളും",
    "Wishlist":"വിഷ്‌ലിസ്റ്റ്",
    "Customer":"ഉപഭോക്താവ്",
    "My Account":"എന്റെ അക്കൗണ്ട്",
    "My Orders":"എന്റെ ഓർഡറുകൾ",
    "My Cart":"എന്റെ കാർട്ട്",
    "Seller":"വിൽപ്പനക്കാരൻ",
    "Seller Dashboard":"വിൽപ്പനക്കാരന്റെ ഡാഷ്ബോർഡ്",
    "Support":"സഹായം",
    "About Us":"ഞങ്ങളെക്കുറിച്ച്",
    "Privacy":"സ്വകാര്യത",
    "Terms":"നിബന്ധനകൾ",
    "Contact":"ബന്ധപ്പെടുക",
    "Categories":"വിഭാഗങ്ങൾ",
    "Account":"അക്കൗണ്ട്"
  },

  Punjabi: {
    "Search for Products, Brands and More":"ਉਤਪਾਦ, ਬ੍ਰਾਂਡ ਅਤੇ ਹੋਰ ਖੋਜੋ",
    "👤 Login":"👤 ਲੌਗਇਨ",
    "Sell on PS Mart":"PS Mart 'ਤੇ ਵੇਚੋ",
    "🛒 Cart":"🛒 ਕਾਰਟ",
    "Delivery location":"ਡਿਲਿਵਰੀ ਸਥਾਨ",
    "Select your location →":"ਆਪਣਾ ਸਥਾਨ ਚੁਣੋ →",
    "For You":"ਤੁਹਾਡੇ ਲਈ",
    "Mobiles":"ਮੋਬਾਈਲ",
    "Fashion":"ਫੈਸ਼ਨ",
    "Electronics":"ਇਲੈਕਟ੍ਰਾਨਿਕਸ",
    "Beauty":"ਬਿਊਟੀ",
    "Home":"ਘਰ",
    "Grocery":"ਕਿਰਿਆਨਾ",
    "Accessories":"ਐਕਸੈਸਰੀਜ਼",
    "PS MART EXCLUSIVE":"PS MART ਖਾਸ",
    "Big Deals":"ਵੱਡੀਆਂ ਆਫ਼ਰਾਂ",
    "Every Day":"ਹਰ ਰੋਜ਼",
    "Shop Now →":"ਹੁਣੇ ਖਰੀਦੋ →",
    "OFF":"ਛੂਟ",
    "Electronics Sale":"ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਸੇਲ",
    "Best deals on gadgets":"ਗੈਜੇਟਸ 'ਤੇ ਵਧੀਆ ਆਫ਼ਰ",
    "Fashion Deals":"ਫੈਸ਼ਨ ਆਫ਼ਰ",
    "Style at better prices":"ਵਧੀਆ ਕੀਮਤ 'ਤੇ ਸਟਾਈਲ",
    "Home Essentials":"ਘਰ ਦੀਆਂ ਜ਼ਰੂਰੀ ਚੀਜ਼ਾਂ",
    "Upgrade your home":"ਆਪਣਾ ਘਰ ਅਪਗ੍ਰੇਡ ਕਰੋ",
    "Best Deals For You 🔥":"ਤੁਹਾਡੇ ਲਈ ਵਧੀਆ ਆਫ਼ਰ 🔥",
    "View All →":"ਸਭ ਵੇਖੋ →",
    "Fast Delivery":"ਤੇਜ਼ ਡਿਲਿਵਰੀ",
    "Reliable delivery":"ਭਰੋਸੇਯੋਗ ਡਿਲਿਵਰੀ",
    "Secure Payment":"ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ",
    "Safe checkout":"ਸੁਰੱਖਿਅਤ ਚੈਕਆਉਟ",
    "Easy Returns":"ਆਸਾਨ ਰਿਟਰਨ",
    "Simple returns":"ਸੌਖੇ ਰਿਟਰਨ",
    "Customer Support":"ਗਾਹਕ ਸਹਾਇਤਾ",
    "Help when needed":"ਲੋੜ ਪੈਣ 'ਤੇ ਮਦਦ",
    "All Products":"ਸਾਰੇ ਉਤਪਾਦ",
    "Wishlist":"ਵਿਸ਼ਲਿਸਟ",
    "Customer":"ਗਾਹਕ",
    "My Account":"ਮੇਰਾ ਖਾਤਾ",
    "My Orders":"ਮੇਰੇ ਆਰਡਰ",
    "My Cart":"ਮੇਰੀ ਕਾਰਟ",
    "Seller":"ਵਿਕਰੇਤਾ",
    "Seller Dashboard":"ਵਿਕਰੇਤਾ ਡੈਸ਼ਬੋਰਡ",
    "Support":"ਸਹਾਇਤਾ",
    "About Us":"ਸਾਡੇ ਬਾਰੇ",
    "Privacy":"ਪਰਾਈਵੇਸੀ",
    "Terms":"ਨਿਯਮ",
    "Contact":"ਸੰਪਰਕ",
    "Categories":"ਸ਼੍ਰੇਣੀਆਂ",
    "Account":"ਖਾਤਾ"
  },

  Urdu: {
    "Search for Products, Brands and More":"پروڈکٹس، برانڈز اور مزید تلاش کریں",
    "👤 Login":"👤 لاگ اِن",
    "Sell on PS Mart":"PS Mart پر فروخت کریں",
    "🛒 Cart":"🛒 کارٹ",
    "Delivery location":"ڈیلیوری کا مقام",
    "Select your location →":"اپنا مقام منتخب کریں →",
    "For You":"آپ کے لیے",
    "Mobiles":"موبائلز",
    "Fashion":"فیشن",
    "Electronics":"الیکٹرانکس",
    "Beauty":"خوبصورتی",
    "Home":"گھر",
    "Grocery":"کریانہ",
    "Accessories":"لوازمات",
    "PS MART EXCLUSIVE":"PS MART خصوصی",
    "Big Deals":"بڑی آفرز",
    "Every Day":"ہر روز",
    "Shop Now →":"ابھی خریدیں →",
    "OFF":"رعایت",
    "Electronics Sale":"الیکٹرانکس سیل",
    "Best deals on gadgets":"گیجٹس پر بہترین آفرز",
    "Fashion Deals":"فیشن آفرز",
    "Style at better prices":"بہتر قیمت پر اسٹائل",
    "Home Essentials":"گھر کی ضروری اشیاء",
    "Upgrade your home":"اپنا گھر بہتر بنائیں",
    "Best Deals For You 🔥":"آپ کے لیے بہترین آفرز 🔥",
    "View All →":"سب دیکھیں →",
    "Fast Delivery":"تیز ڈیلیوری",
    "Reliable delivery":"قابل اعتماد ڈیلیوری",
    "Secure Payment":"محفوظ ادائیگی",
    "Safe checkout":"محفوظ چیک آؤٹ",
    "Easy Returns":"آسان واپسی",
    "Simple returns":"آسان ریٹرن",
    "Customer Support":"کسٹمر سپورٹ",
    "Help when needed":"ضرورت پر مدد",
    "All Products":"تمام پروڈکٹس",
    "Wishlist":"خواہشات کی فہرست",
    "Customer":"گاہک",
    "My Account":"میرا اکاؤنٹ",
    "My Orders":"میرے آرڈرز",
    "My Cart":"میرا کارٹ",
    "Seller":"فروخت کنندہ",
    "Seller Dashboard":"سیلر ڈیش بورڈ",
    "Support":"مدد",
    "About Us":"ہمارے بارے میں",
    "Privacy":"رازداری",
    "Terms":"شرائط",
    "Contact":"رابطہ",
    "Categories":"زمرے",
    "Account":"اکاؤنٹ"
  },

  Odia: {
    "Search for Products, Brands and More":"ଉତ୍ପାଦ, ବ୍ରାଣ୍ଡ ଏବଂ ଅଧିକ ଖୋଜନ୍ତୁ",
    "👤 Login":"👤 ଲଗଇନ୍",
    "Sell on PS Mart":"PS Mart ରେ ବିକ୍ରି କରନ୍ତୁ",
    "🛒 Cart":"🛒 କାର୍ଟ",
    "Delivery location":"ଡେଲିଭରୀ ସ୍ଥାନ",
    "Select your location →":"ଆପଣଙ୍କ ସ୍ଥାନ ବାଛନ୍ତୁ →",
    "For You":"ଆପଣଙ୍କ ପାଇଁ",
    "Mobiles":"ମୋବାଇଲ୍",
    "Fashion":"ଫ୍ୟାଶନ୍",
    "Electronics":"ଇଲେକ୍ଟ୍ରୋନିକ୍ସ",
    "Beauty":"ବିୟୁଟି",
    "Home":"ଘର",
    "Grocery":"କିରାଣା",
    "Accessories":"ଆକ୍ସେସରିଜ୍",
    "PS MART EXCLUSIVE":"PS MART ବିଶେଷ",
    "Big Deals":"ବଡ଼ ଅଫର୍",
    "Every Day":"ପ୍ରତିଦିନ",
    "Shop Now →":"ବର୍ତ୍ତମାନ କିଣନ୍ତୁ →",
    "OFF":"ଛାଡ଼",
    "Electronics Sale":"ଇଲେକ୍ଟ୍ରୋନିକ୍ସ ସେଲ୍",
    "Best deals on gadgets":"ଗ୍ୟାଜେଟ୍ ଉପରେ ସର୍ବୋତ୍ତମ ଅଫର୍",
    "Fashion Deals":"ଫ୍ୟାଶନ୍ ଅଫର୍",
    "Style at better prices":"ଭଲ ମୂଲ୍ୟରେ ଷ୍ଟାଇଲ୍",
    "Home Essentials":"ଘରୋଇ ଆବଶ୍ୟକତା",
    "Upgrade your home":"ଆପଣଙ୍କ ଘରକୁ ଅପଗ୍ରେଡ୍ କରନ୍ତୁ",
    "Best Deals For You 🔥":"ଆପଣଙ୍କ ପାଇଁ ସର୍ବୋତ୍ତମ ଅଫର୍ 🔥",
    "View All →":"ସମସ୍ତ ଦେଖନ୍ତୁ →",
    "Fast Delivery":"ଦ୍ରୁତ ଡେଲିଭରୀ",
    "Reliable delivery":"ଭରସାଯୋଗ୍ୟ ଡେଲିଭରୀ",
    "Secure Payment":"ସୁରକ୍ଷିତ ପେମେଣ୍ଟ",
    "Safe checkout":"ସୁରକ୍ଷିତ ଚେକଆଉଟ୍",
    "Easy Returns":"ସହଜ ରିଟର୍ନ",
    "Simple returns":"ସରଳ ରିଟର୍ନ",
    "Customer Support":"ଗ୍ରାହକ ସହାୟତା",
    "Help when needed":"ଆବଶ୍ୟକ ସମୟରେ ସାହାଯ୍ୟ",
    "All Products":"ସମସ୍ତ ଉତ୍ପାଦ",
    "Wishlist":"ୱିଶଲିଷ୍ଟ",
    "Customer":"ଗ୍ରାହକ",
    "My Account":"ମୋ ଆକାଉଣ୍ଟ",
    "My Orders":"ମୋ ଅର୍ଡର",
    "My Cart":"ମୋ କାର୍ଟ",
    "Seller":"ବିକ୍ରେତା",
    "Seller Dashboard":"ବିକ୍ରେତା ଡ୍ୟାଶବୋର୍ଡ",
    "Support":"ସହାୟତା",
    "About Us":"ଆମ ବିଷୟରେ",
    "Privacy":"ଗୋପନୀୟତା",
    "Terms":"ନିୟମ",
    "Contact":"ଯୋଗାଯୋଗ",
    "Categories":"ବର୍ଗ",
    "Account":"ଆକାଉଣ୍ଟ"
  },

  Assamese: {
    "Search for Products, Brands and More":"প্ৰডাক্ট, ব্ৰেণ্ড আৰু অধিক বিচাৰক",
    "👤 Login":"👤 লগইন",
    "Sell on PS Mart":"PS Mart-ত বিক্ৰী কৰক",
    "🛒 Cart":"🛒 কাৰ্ট",
    "Delivery location":"ডেলিভাৰী স্থান",
    "Select your location →":"আপোনাৰ স্থান বাছক →",
    "For You":"আপোনাৰ বাবে",
    "Mobiles":"ম'বাইল",
    "Fashion":"ফেশ্বন",
    "Electronics":"ইলেক্ট্ৰনিকছ",
    "Beauty":"বিউটি",
    "Home":"ঘৰ",
    "Grocery":"গ্ৰচাৰী",
    "Accessories":"এচেচৰিজ",
    "PS MART EXCLUSIVE":"PS MART বিশেষ",
    "Big Deals":"ডাঙৰ অফাৰ",
    "Every Day":"প্ৰতিদিনে",
    "Shop Now →":"এতিয়াই কিনক →",
    "OFF":"ৰেহাই",
    "Electronics Sale":"ইলেক্ট্ৰনিকছ ছেল",
    "Best deals on gadgets":"গেজেটত সৰ্বোত্তম অফাৰ",
    "Fashion Deals":"ফেশ্বন অফাৰ",
    "Style at better prices":"ভাল মূল্যত ষ্টাইল",
    "Home Essentials":"ঘৰৰ প্ৰয়োজনীয় সামগ্ৰী",
    "Upgrade your home":"আপোনাৰ ঘৰ উন্নত কৰক",
    "Best Deals For You 🔥":"আপোনাৰ বাবে সৰ্বোত্তম অফাৰ 🔥",
    "View All →":"সকলো চাওক →",
    "Fast Delivery":"দ্ৰুত ডেলিভাৰী",
    "Reliable delivery":"বিশ্বাসযোগ্য ডেলিভাৰী",
    "Secure Payment":"সুৰক্ষিত পেমেণ্ট",
    "Safe checkout":"সুৰক্ষিত চেকআউট",
    "Easy Returns":"সহজ ৰিটাৰ্ণ",
    "Simple returns":"সহজ ৰিটাৰ্ণ",
    "Customer Support":"গ্ৰাহক সহায়তা",
    "Help when needed":"প্ৰয়োজনত সহায়",
    "All Products":"সকলো প্ৰডাক্ট",
    "Wishlist":"উইশলিষ্ট",
    "Customer":"গ্ৰাহক",
    "My Account":"মোৰ একাউণ্ট",
    "My Orders":"মোৰ অৰ্ডাৰ",
    "My Cart":"মোৰ কাৰ্ট",
    "Seller":"বিক্ৰেতা",
    "Seller Dashboard":"বিক্ৰেতা ডেশ্বব'ৰ্ড",
    "Support":"সহায়তা",
    "About Us":"আমাৰ বিষয়ে",
    "Privacy":"গোপনীয়তা",
    "Terms":"নিয়ম",
    "Contact":"যোগাযোগ",
    "Categories":"শ্ৰেণী",
    "Account":"একাউণ্ট"
  },

  French: {
    "Search for Products, Brands and More":"Rechercher des produits, marques et plus",
    "👤 Login":"👤 Connexion",
    "Sell on PS Mart":"Vendre sur PS Mart",
    "🛒 Cart":"🛒 Panier",
    "Delivery location":"Lieu de livraison",
    "Select your location →":"Sélectionnez votre emplacement →",
    "For You":"Pour vous",
    "Mobiles":"Mobiles",
    "Fashion":"Mode",
    "Electronics":"Électronique",
    "Beauty":"Beauté",
    "Home":"Maison",
    "Grocery":"Épicerie",
    "Accessories":"Accessoires",
    "PS MART EXCLUSIVE":"EXCLUSIVITÉ PS MART",
    "Big Deals":"Grosses offres",
    "Every Day":"Chaque jour",
    "Shop Now →":"Acheter maintenant →",
    "OFF":"REMISE",
    "Electronics Sale":"Soldes électroniques",
    "Best deals on gadgets":"Meilleures offres sur les gadgets",
    "Fashion Deals":"Offres mode",
    "Style at better prices":"Le style à meilleur prix",
    "Home Essentials":"Essentiels pour la maison",
    "Upgrade your home":"Améliorez votre maison",
    "Best Deals For You 🔥":"Meilleures offres pour vous 🔥",
    "View All →":"Tout voir →",
    "Fast Delivery":"Livraison rapide",
    "Reliable delivery":"Livraison fiable",
    "Secure Payment":"Paiement sécurisé",
    "Safe checkout":"Paiement sécurisé",
    "Easy Returns":"Retours faciles",
    "Simple returns":"Retours simples",
    "Customer Support":"Service client",
    "Help when needed":"Aide quand nécessaire",
    "All Products":"Tous les produits",
    "Wishlist":"Liste de souhaits",
    "Customer":"Client",
    "My Account":"Mon compte",
    "My Orders":"Mes commandes",
    "My Cart":"Mon panier",
    "Seller":"Vendeur",
    "Seller Dashboard":"Tableau de bord vendeur",
    "Support":"Assistance",
    "About Us":"À propos de nous",
    "Privacy":"Confidentialité",
    "Terms":"Conditions",
    "Contact":"Contact",
    "Categories":"Catégories",
    "Account":"Compte"
  },

  German: {
    "Search for Products, Brands and More":"Produkte, Marken und mehr suchen",
    "👤 Login":"👤 Anmelden",
    "Sell on PS Mart":"Auf PS Mart verkaufen",
    "🛒 Cart":"🛒 Warenkorb",
    "Delivery location":"Lieferort",
    "Select your location →":"Standort auswählen →",
    "For You":"Für Sie",
    "Mobiles":"Handys",
    "Fashion":"Mode",
    "Electronics":"Elektronik",
    "Beauty":"Beauty",
    "Home":"Haushalt",
    "Grocery":"Lebensmittel",
    "Accessories":"Zubehör",
    "PS MART EXCLUSIVE":"PS MART EXKLUSIV",
    "Big Deals":"Große Angebote",
    "Every Day":"Jeden Tag",
    "Shop Now →":"Jetzt einkaufen →",
    "OFF":"RABATT",
    "Electronics Sale":"Elektronik-Angebote",
    "Best deals on gadgets":"Beste Angebote für Gadgets",
    "Fashion Deals":"Mode-Angebote",
    "Style at better prices":"Style zu besseren Preisen",
    "Home Essentials":"Haushaltsbedarf",
    "Upgrade your home":"Verbessern Sie Ihr Zuhause",
    "Best Deals For You 🔥":"Beste Angebote für Sie 🔥",
    "View All →":"Alle ansehen →",
    "Fast Delivery":"Schnelle Lieferung",
    "Reliable delivery":"Zuverlässige Lieferung",
    "Secure Payment":"Sichere Zahlung",
    "Safe checkout":"Sicherer Checkout",
    "Easy Returns":"Einfache Rückgabe",
    "Simple returns":"Einfache Rückgaben",
    "Customer Support":"Kundensupport",
    "Help when needed":"Hilfe bei Bedarf",
    "All Products":"Alle Produkte",
    "Wishlist":"Wunschliste",
    "Customer":"Kunde",
    "My Account":"Mein Konto",
    "My Orders":"Meine Bestellungen",
    "My Cart":"Mein Warenkorb",
    "Seller":"Verkäufer",
    "Seller Dashboard":"Verkäufer-Dashboard",
    "Support":"Support",
    "About Us":"Über uns",
    "Privacy":"Datenschutz",
    "Terms":"Bedingungen",
    "Contact":"Kontakt",
    "Categories":"Kategorien",
    "Account":"Konto"
  },

  Spanish: {
    "Search for Products, Brands and More":"Buscar productos, marcas y más",
    "👤 Login":"👤 Iniciar sesión",
    "Sell on PS Mart":"Vender en PS Mart",
    "🛒 Cart":"🛒 Carrito",
    "Delivery location":"Ubicación de entrega",
    "Select your location →":"Selecciona tu ubicación →",
    "For You":"Para ti",
    "Mobiles":"Móviles",
    "Fashion":"Moda",
    "Electronics":"Electrónica",
    "Beauty":"Belleza",
    "Home":"Hogar",
    "Grocery":"Comestibles",
    "Accessories":"Accesorios",
    "PS MART EXCLUSIVE":"EXCLUSIVO DE PS MART",
    "Big Deals":"Grandes ofertas",
    "Every Day":"Todos los días",
    "Shop Now →":"Comprar ahora →",
    "OFF":"DESCUENTO",
    "Electronics Sale":"Oferta de electrónica",
    "Best deals on gadgets":"Mejores ofertas en gadgets",
    "Fashion Deals":"Ofertas de moda",
    "Style at better prices":"Estilo a mejores precios",
    "Home Essentials":"Artículos esenciales para el hogar",
    "Upgrade your home":"Mejora tu hogar",
    "Best Deals For You 🔥":"Las mejores ofertas para ti 🔥",
    "View All →":"Ver todo →",
    "Fast Delivery":"Entrega rápida",
    "Reliable delivery":"Entrega confiable",
    "Secure Payment":"Pago seguro",
    "Safe checkout":"Compra segura",
    "Easy Returns":"Devoluciones fáciles",
    "Simple returns":"Devoluciones sencillas",
    "Customer Support":"Atención al cliente",
    "Help when needed":"Ayuda cuando la necesites",
    "All Products":"Todos los productos",
    "Wishlist":"Lista de deseos",
    "Customer":"Cliente",
    "My Account":"Mi cuenta",
    "My Orders":"Mis pedidos",
    "My Cart":"Mi carrito",
    "Seller":"Vendedor",
    "Seller Dashboard":"Panel del vendedor",
    "Support":"Soporte",
    "About Us":"Sobre nosotros",
    "Privacy":"Privacidad",
    "Terms":"Términos",
    "Contact":"Contacto",
    "Categories":"Categorías",
    "Account":"Cuenta"
  },

  Italian: {
    "Search for Products, Brands and More":"Cerca prodotti, marche e altro",
    "👤 Login":"👤 Accedi",
    "Sell on PS Mart":"Vendi su PS Mart",
    "🛒 Cart":"🛒 Carrello",
    "Delivery location":"Luogo di consegna",
    "Select your location →":"Seleziona la tua posizione →",
    "For You":"Per te",
    "Mobiles":"Cellulari",
    "Fashion":"Moda",
    "Electronics":"Elettronica",
    "Beauty":"Bellezza",
    "Home":"Casa",
    "Grocery":"Alimentari",
    "Accessories":"Accessori",
    "PS MART EXCLUSIVE":"ESCLUSIVA PS MART",
    "Big Deals":"Grandi offerte",
    "Every Day":"Ogni giorno",
    "Shop Now →":"Acquista ora →",
    "OFF":"SCONTO",
    "Electronics Sale":"Offerte elettronica",
    "Best deals on gadgets":"Le migliori offerte sui gadget",
    "Fashion Deals":"Offerte moda",
    "Style at better prices":"Stile a prezzi migliori",
    "Home Essentials":"Essenziali per la casa",
    "Upgrade your home":"Migliora la tua casa",
    "Best Deals For You 🔥":"Le migliori offerte per te 🔥",
    "View All →":"Vedi tutto →",
    "Fast Delivery":"Consegna rapida",
    "Reliable delivery":"Consegna affidabile",
    "Secure Payment":"Pagamento sicuro",
    "Safe checkout":"Checkout sicuro",
    "Easy Returns":"Resi facili",
    "Simple returns":"Resi semplici",
    "Customer Support":"Assistenza clienti",
    "Help when needed":"Aiuto quando serve",
    "All Products":"Tutti i prodotti",
    "Wishlist":"Lista desideri",
    "Customer":"Cliente",
    "My Account":"Il mio account",
    "My Orders":"I miei ordini",
    "My Cart":"Il mio carrello",
    "Seller":"Venditore",
    "Seller Dashboard":"Dashboard venditore",
    "Support":"Supporto",
    "About Us":"Chi siamo",
    "Privacy":"Privacy",
    "Terms":"Termini",
    "Contact":"Contatti",
    "Categories":"Categorie",
    "Account":"Account"
  },

  Japanese: {
    "Search for Products, Brands and More":"商品、ブランドなどを検索",
    "👤 Login":"👤 ログイン",
    "Sell on PS Mart":"PS Martで販売",
    "🛒 Cart":"🛒 カート",
    "Delivery location":"配送先",
    "Select your location →":"配送先を選択 →",
    "For You":"あなたへのおすすめ",
    "Mobiles":"スマートフォン",
    "Fashion":"ファッション",
    "Electronics":"電子機器",
    "Beauty":"美容",
    "Home":"ホーム",
    "Grocery":"食品",
    "Accessories":"アクセサリー",
    "PS MART EXCLUSIVE":"PS MART限定",
    "Big Deals":"お得なセール",
    "Every Day":"毎日",
    "Shop Now →":"今すぐ購入 →",
    "OFF":"割引",
    "Electronics Sale":"電子機器セール",
    "Best deals on gadgets":"ガジェットのお得な商品",
    "Fashion Deals":"ファッションセール",
    "Style at better prices":"お得な価格でスタイル",
    "Home Essentials":"ホーム用品",
    "Upgrade your home":"お家をアップグレード",
    "Best Deals For You 🔥":"あなたへのおすすめ 🔥",
    "View All →":"すべて見る →",
    "Fast Delivery":"迅速な配送",
    "Reliable delivery":"安心の配送",
    "Secure Payment":"安全な支払い",
    "Safe checkout":"安全なチェックアウト",
    "Easy Returns":"簡単返品",
    "Simple returns":"簡単な返品",
    "Customer Support":"カスタマーサポート",
    "Help when needed":"必要なときのサポート",
    "All Products":"すべての商品",
    "Wishlist":"お気に入り",
    "Customer":"お客様",
    "My Account":"マイアカウント",
    "My Orders":"注文履歴",
    "My Cart":"マイカート",
    "Seller":"販売者",
    "Seller Dashboard":"販売者ダッシュボード",
    "Support":"サポート",
    "About Us":"私たちについて",
    "Privacy":"プライバシー",
    "Terms":"利用規約",
    "Contact":"お問い合わせ",
    "Categories":"カテゴリー",
    "Account":"アカウント"
  },

  Chinese: {
    "Search for Products, Brands and More":"搜索商品、品牌及更多",
    "👤 Login":"👤 登录",
    "Sell on PS Mart":"在 PS Mart 上销售",
    "🛒 Cart":"🛒 购物车",
    "Delivery location":"配送地址",
    "Select your location →":"选择您的位置 →",
    "For You":"为您推荐",
    "Mobiles":"手机",
    "Fashion":"时尚",
    "Electronics":"电子产品",
    "Beauty":"美妆",
    "Home":"家居",
    "Grocery":"杂货",
    "Accessories":"配件",
    "PS MART EXCLUSIVE":"PS MART 独家",
    "Big Deals":"超值优惠",
    "Every Day":"每天",
    "Shop Now →":"立即购买 →",
    "OFF":"折扣",
    "Electronics Sale":"电子产品优惠",
    "Best deals on gadgets":"数码产品超值优惠",
    "Fashion Deals":"时尚优惠",
    "Style at better prices":"更优惠的价格",
    "Home Essentials":"家居必需品",
    "Upgrade your home":"升级您的家",
    "Best Deals For You 🔥":"为您提供最佳优惠 🔥",
    "View All →":"查看全部 →",
    "Fast Delivery":"快速配送",
    "Reliable delivery":"可靠配送",
    "Secure Payment":"安全支付",
    "Safe checkout":"安全结账",
    "Easy Returns":"轻松退货",
    "Simple returns":"简单退货",
    "Customer Support":"客户支持",
    "Help when needed":"需要时提供帮助",
    "All Products":"所有商品",
    "Wishlist":"收藏夹",
    "Customer":"客户",
    "My Account":"我的账户",
    "My Orders":"我的订单",
    "My Cart":"我的购物车",
    "Seller":"卖家",
    "Seller Dashboard":"卖家中心",
    "Support":"支持",
    "About Us":"关于我们",
    "Privacy":"隐私",
    "Terms":"条款",
    "Contact":"联系我们",
    "Categories":"分类",
    "Account":"账户"
  },

  Korean: {
    "Search for Products, Brands and More":"상품, 브랜드 및 기타 검색",
    "👤 Login":"👤 로그인",
    "Sell on PS Mart":"PS Mart에서 판매",
    "🛒 Cart":"🛒 장바구니",
    "Delivery location":"배송 위치",
    "Select your location →":"위치를 선택하세요 →",
    "For You":"추천 상품",
    "Mobiles":"모바일",
    "Fashion":"패션",
    "Electronics":"전자제품",
    "Beauty":"뷰티",
    "Home":"홈",
    "Grocery":"식료품",
    "Accessories":"액세서리",
    "PS MART EXCLUSIVE":"PS MART 독점",
    "Big Deals":"특가 상품",
    "Every Day":"매일",
    "Shop Now →":"지금 쇼핑하기 →",
    "OFF":"할인",
    "Electronics Sale":"전자제품 할인",
    "Best deals on gadgets":"가젯 특가",
    "Fashion Deals":"패션 특가",
    "Style at better prices":"더 좋은 가격의 스타일",
    "Home Essentials":"생활 필수품",
    "Upgrade your home":"집을 업그레이드하세요",
    "Best Deals For You 🔥":"당신을 위한 최고의 상품 🔥",
    "View All →":"모두 보기 →",
    "Fast Delivery":"빠른 배송",
    "Reliable delivery":"믿을 수 있는 배송",
    "Secure Payment":"안전한 결제",
    "Safe checkout":"안전한 체크아웃",
    "Easy Returns":"간편한 반품",
    "Simple returns":"간단한 반품",
    "Customer Support":"고객 지원",
    "Help when needed":"필요할 때 도움",
    "All Products":"모든 상품",
    "Wishlist":"위시리스트",
    "Customer":"고객",
    "My Account":"내 계정",
    "My Orders":"내 주문",
    "My Cart":"내 장바구니",
    "Seller":"판매자",
    "Seller Dashboard":"판매자 대시보드",
    "Support":"지원",
    "About Us":"회사 소개",
    "Privacy":"개인정보 보호",
    "Terms":"약관",
    "Contact":"연락처",
    "Categories":"카테고리",
    "Account":"계정"
  }

};


/* =====================================================
   TRANSLATE CURRENT PAGE
===================================================== */

/* =====================================================
   PS MART - TRANSLATION ENGINE
===================================================== */

function translatePage() {

  const language = localStorage.getItem("psmart-language");

  // English = original
  if (!language || language === "English") {
    return;
  }

  const translations = PS_TRANSLATIONS[language];

  if (!translations) {
    console.log("Translation not found:", language);
    return;
  }

  /* -----------------------------
     TEXT TRANSLATION
  ----------------------------- */

  const walker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_TEXT
  );

  const nodes = [];

  let node;

  while ((node = walker.nextNode())) {
    nodes.push(node);
  }

  nodes.forEach(function(textNode) {

    const originalText = textNode.nodeValue;

    if (!originalText || !originalText.trim()) {
      return;
    }

    const cleanText = originalText.trim();

    if (translations[cleanText]) {

      textNode.nodeValue =
        originalText.replace(
          cleanText,
          translations[cleanText]
        );

    }

  });


  /* -----------------------------
     PLACEHOLDER TRANSLATION
  ----------------------------- */

  document.querySelectorAll(
    "input[placeholder], textarea[placeholder]"
  ).forEach(function(input) {

    const original = input.getAttribute("placeholder");

    if (translations[original]) {

      input.setAttribute(
        "placeholder",
        translations[original]
      );

    }

  });


  /* -----------------------------
     HTML LANGUAGE
  ----------------------------- */

  const languageCodes = {
    Hindi: "hi",
    Bengali: "bn",
    Marathi: "mr",
    Telugu: "te",
    Tamil: "ta",
    Gujarati: "gu",
    Kannada: "kn",
    Malayalam: "ml",
    Punjabi: "pa",
    Urdu: "ur",
    Odia: "or",
    Assamese: "as",
    French: "fr",
    German: "de",
    Spanish: "es",
    Italian: "it",
    Japanese: "ja",
    Chinese: "zh",
    Korean: "ko"
  };

  document.documentElement.lang =
    languageCodes[language] || "en";

}


/* =====================================================
   RUN AFTER PAGE LOAD
===================================================== */

document.addEventListener(
  "DOMContentLoaded",
  function() {

    // First translation
    translatePage();

    // App.js ke dynamic content ke liye
    setTimeout(function() {
      translatePage();
    }, 500);

    setTimeout(function() {
      translatePage();
    }, 1500);

  }
);
