/* =====================================================
   PS MART - translate-extra.js
   translate.js ke BAAD load karein. Isme:
   1) naye page ke text ke translations (19 languages)
   2) Hindi poori Devanagari mein
   3) naya translation engine (dynamic products/cart ke liye bhi chalta hai)
===================================================== */

var PS_EXTRA = {
"Hindi": {
"Shop by Category 🛍️": "श्रेणी के अनुसार खरीदें 🛍️",
"⚡ Flash Deals": "⚡ फ्लैश डील्स",
"🔥 Trending Picks": "🔥 ट्रेंडिंग पिक्स",
"✨ New Arrivals": "✨ नए आगमन",
"⚡ LIMITED TIME DEALS": "⚡ सीमित समय के ऑफर",
"Save more on selected products today": "आज चुने हुए प्रोडक्ट्स पर ज़्यादा बचत करें",
"Shop Deals →": "ऑफर देखें →",
"🎁 Get Extra ₹100 OFF": "🎁 ₹100 की एक्स्ट्रा छूट पाएं",
"Use this coupon on your next purchase": "अपनी अगली खरीदारी पर यह कूपन इस्तेमाल करें",
"Copy Code": "कोड कॉपी करें",
"Multiple Payments": "कई पेमेंट विकल्प",
"Choose your method": "अपना तरीका चुनें",
"Secure Shopping": "सुरक्षित शॉपिंग",
"Become a Seller →": "सेलर बनें →",
"Grow your business and reach more customers.": "अपना बिज़नेस बढ़ाएं और ज़्यादा ग्राहकों तक पहुंचें।",
"View Product →": "प्रोडक्ट देखें →",
"No products found": "कोई प्रोडक्ट नहीं मिला",
"Filters": "फ़िल्टर",
"Price": "कीमत",
"Under ₹1,000": "₹1,000 से कम",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "लोकप्रिय",
"Price: Low to High": "कीमत: कम से ज़्यादा",
"Price: High to Low": "कीमत: ज़्यादा से कम",
"☰ All Categories": "☰ सभी श्रेणियां",
"🛒 Add to Cart": "🛒 कार्ट में जोड़ें",
"⚡ Buy Now": "⚡ अभी खरीदें",
"✓ In Stock": "✓ स्टॉक में है",
"✕ Out of Stock": "✕ स्टॉक खत्म",
"Product Description": "प्रोडक्ट विवरण",
"Specifications": "विशेषताएं",
"Your cart is empty 🛒": "आपका कार्ट खाली है 🛒",
"Continue Shopping": "खरीदारी जारी रखें",
"Price Details": "कीमत का विवरण",
"Total": "कुल",
"Proceed to Checkout →": "चेकआउट पर जाएं →",
"❌ Remove": "❌ हटाएं",
"Apply": "लागू करें",
"FREE": "मुफ़्त",
"Search for Products, Brands and More": "प्रोडक्ट्स, ब्रांड्स और बहुत कुछ खोजें",
"👤 Login": "👤 लॉगिन",
"Sell on PS Mart": "PS Mart पर बेचें",
"🛒 Cart": "🛒 कार्ट",
"Delivery location": "डिलीवरी की जगह",
"Select your location →": "अपनी लोकेशन चुनें →",
"For You": "आपके लिए",
"Mobiles": "मोबाइल",
"Fashion": "फ़ैशन",
"Electronics": "इलेक्ट्रॉनिक्स",
"Beauty": "ब्यूटी",
"Home": "होम",
"Grocery": "किराना",
"Accessories": "एक्सेसरीज़",
"PS MART EXCLUSIVE": "PS MART एक्सक्लूसिव",
"Big Deals": "बड़े ऑफर",
"Every Day": "हर दिन",
"Shop Now →": "अभी खरीदें →",
"OFF": "छूट",
"Electronics Sale": "इलेक्ट्रॉनिक्स सेल",
"Best deals on gadgets": "गैजेट्स पर बेहतरीन ऑफर",
"Fashion Deals": "फ़ैशन ऑफर",
"Style at better prices": "बेहतर कीमत पर स्टाइल",
"Home Essentials": "घर की ज़रूरी चीज़ें",
"Upgrade your home": "अपने घर को अपग्रेड करें",
"Best Deals For You 🔥": "आपके लिए बेस्ट डील्स 🔥",
"View All →": "सभी देखें →",
"Fast Delivery": "तेज़ डिलीवरी",
"Reliable delivery": "भरोसेमंद डिलीवरी",
"Secure Payment": "सुरक्षित पेमेंट",
"Safe checkout": "सुरक्षित चेकआउट",
"Easy Returns": "आसान रिटर्न",
"Simple returns": "सरल रिटर्न",
"Customer Support": "ग्राहक सहायता",
"Help when needed": "ज़रूरत पर मदद",
"All Products": "सभी प्रोडक्ट्स",
"Wishlist": "विशलिस्ट",
"Customer": "ग्राहक",
"My Account": "मेरा अकाउंट",
"My Orders": "मेरे ऑर्डर",
"My Cart": "मेरा कार्ट",
"Seller": "सेलर",
"Seller Dashboard": "सेलर डैशबोर्ड",
"Support": "सहायता",
"About Us": "हमारे बारे में",
"Privacy": "प्राइवेसी",
"Terms": "शर्तें",
"Contact": "संपर्क",
"Categories": "श्रेणियां",
"Account": "अकाउंट"
},
"Bengali": {
"Shop by Category 🛍️": "শ্রেণি অনুযায়ী কিনুন 🛍️",
"⚡ Flash Deals": "⚡ ফ্ল্যাশ ডিল",
"🔥 Trending Picks": "🔥 ট্রেন্ডিং পিকস",
"✨ New Arrivals": "✨ নতুন আগমন",
"⚡ LIMITED TIME DEALS": "⚡ সীমিত সময়ের অফার",
"Save more on selected products today": "আজ নির্বাচিত পণ্যে আরও সাশ্রয় করুন",
"Shop Deals →": "অফার দেখুন →",
"🎁 Get Extra ₹100 OFF": "🎁 অতিরিক্ত ₹100 ছাড় পান",
"Use this coupon on your next purchase": "পরবর্তী কেনাকাটায় এই কুপন ব্যবহার করুন",
"Copy Code": "কোড কপি করুন",
"Multiple Payments": "একাধিক পেমেন্ট",
"Choose your method": "আপনার পদ্ধতি বেছে নিন",
"Secure Shopping": "নিরাপদ শপিং",
"Become a Seller →": "বিক্রেতা হন →",
"Grow your business and reach more customers.": "আপনার ব্যবসা বাড়ান এবং আরও গ্রাহকের কাছে পৌঁছান।",
"View Product →": "পণ্য দেখুন →",
"No products found": "কোনো পণ্য পাওয়া যায়নি",
"Filters": "ফিল্টার",
"Price": "দাম",
"Under ₹1,000": "₹1,000-এর কম",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "জনপ্রিয়",
"Price: Low to High": "দাম: কম থেকে বেশি",
"Price: High to Low": "দাম: বেশি থেকে কম",
"☰ All Categories": "☰ সব ক্যাটাগরি",
"🛒 Add to Cart": "🛒 কার্টে যোগ করুন",
"⚡ Buy Now": "⚡ এখনই কিনুন",
"✓ In Stock": "✓ স্টকে আছে",
"✕ Out of Stock": "✕ স্টক নেই",
"Product Description": "পণ্যের বিবরণ",
"Specifications": "বৈশিষ্ট্য",
"Your cart is empty 🛒": "আপনার কার্ট খালি 🛒",
"Continue Shopping": "কেনাকাটা চালিয়ে যান",
"Price Details": "দামের বিবরণ",
"Total": "মোট",
"Proceed to Checkout →": "চেকআউটে যান →",
"❌ Remove": "❌ সরান",
"Apply": "প্রয়োগ করুন",
"FREE": "বিনামূল্যে"
},
"Marathi": {
"Shop by Category 🛍️": "श्रेणीनुसार खरेदी करा 🛍️",
"⚡ Flash Deals": "⚡ फ्लॅश डील्स",
"🔥 Trending Picks": "🔥 ट्रेंडिंग निवडी",
"✨ New Arrivals": "✨ नवीन आगमन",
"⚡ LIMITED TIME DEALS": "⚡ मर्यादित वेळेच्या ऑफर्स",
"Save more on selected products today": "आज निवडक उत्पादनांवर जास्त बचत करा",
"Shop Deals →": "ऑफर्स पहा →",
"🎁 Get Extra ₹100 OFF": "🎁 ₹100 अतिरिक्त सूट मिळवा",
"Use this coupon on your next purchase": "पुढील खरेदीवर हा कूपन वापरा",
"Copy Code": "कोड कॉपी करा",
"Multiple Payments": "अनेक पेमेंट पर्याय",
"Choose your method": "तुमची पद्धत निवडा",
"Secure Shopping": "सुरक्षित खरेदी",
"Become a Seller →": "विक्रेता व्हा →",
"Grow your business and reach more customers.": "तुमचा व्यवसाय वाढवा आणि अधिक ग्राहकांपर्यंत पोहोचा.",
"View Product →": "उत्पादन पहा →",
"No products found": "कोणतेही उत्पादन सापडले नाही",
"Filters": "फिल्टर",
"Price": "किंमत",
"Under ₹1,000": "₹1,000 पेक्षा कमी",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "लोकप्रिय",
"Price: Low to High": "किंमत: कमी ते जास्त",
"Price: High to Low": "किंमत: जास्त ते कमी",
"☰ All Categories": "☰ सर्व श्रेणी",
"🛒 Add to Cart": "🛒 कार्टमध्ये जोडा",
"⚡ Buy Now": "⚡ आता खरेदी करा",
"✓ In Stock": "✓ स्टॉकमध्ये आहे",
"✕ Out of Stock": "✕ स्टॉक संपला",
"Product Description": "उत्पादनाचे वर्णन",
"Specifications": "वैशिष्ट्ये",
"Your cart is empty 🛒": "तुमची कार्ट रिकामी आहे 🛒",
"Continue Shopping": "खरेदी सुरू ठेवा",
"Price Details": "किमतीचा तपशील",
"Total": "एकूण",
"Proceed to Checkout →": "चेकआउटकडे जा →",
"❌ Remove": "❌ काढा",
"Apply": "लागू करा",
"FREE": "मोफत"
},
"Telugu": {
"Shop by Category 🛍️": "వర్గం ప్రకారం కొనండి 🛍️",
"⚡ Flash Deals": "⚡ ఫ్లాష్ డీల్స్",
"🔥 Trending Picks": "🔥 ట్రెండింగ్ ఎంపికలు",
"✨ New Arrivals": "✨ కొత్త ఉత్పత్తులు",
"⚡ LIMITED TIME DEALS": "⚡ పరిమిత సమయ ఆఫర్లు",
"Save more on selected products today": "ఈరోజు ఎంపిక చేసిన ఉత్పత్తులపై మరింత ఆదా చేయండి",
"Shop Deals →": "ఆఫర్లు చూడండి →",
"🎁 Get Extra ₹100 OFF": "🎁 అదనంగా ₹100 తగ్గింపు పొందండి",
"Use this coupon on your next purchase": "మీ తదుపరి కొనుగోలుపై ఈ కూపన్ వాడండి",
"Copy Code": "కోడ్ కాపీ చేయండి",
"Multiple Payments": "పలు చెల్లింపు పద్ధతులు",
"Choose your method": "మీ పద్ధతిని ఎంచుకోండి",
"Secure Shopping": "సురక్షిత షాపింగ్",
"Become a Seller →": "విక్రేతగా మారండి →",
"Grow your business and reach more customers.": "మీ వ్యాపారాన్ని పెంచుకోండి, మరింత మంది కస్టమర్లను చేరుకోండి.",
"View Product →": "ఉత్పత్తి చూడండి →",
"No products found": "ఉత్పత్తులు కనపడలేదు",
"Filters": "ఫిల్టర్లు",
"Price": "ధర",
"Under ₹1,000": "₹1,000 కంటే తక్కువ",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "ప్రజాదరణ",
"Price: Low to High": "ధర: తక్కువ నుండి ఎక్కువ",
"Price: High to Low": "ధర: ఎక్కువ నుండి తక్కువ",
"☰ All Categories": "☰ అన్ని వర్గాలు",
"🛒 Add to Cart": "🛒 కార్ట్‌కు జోడించండి",
"⚡ Buy Now": "⚡ ఇప్పుడే కొనండి",
"✓ In Stock": "✓ స్టాక్‌లో ఉంది",
"✕ Out of Stock": "✕ స్టాక్ లేదు",
"Product Description": "ఉత్పత్తి వివరణ",
"Specifications": "స్పెసిఫికేషన్లు",
"Your cart is empty 🛒": "మీ కార్ట్ ఖాళీగా ఉంది 🛒",
"Continue Shopping": "షాపింగ్ కొనసాగించండి",
"Price Details": "ధర వివరాలు",
"Total": "మొత్తం",
"Proceed to Checkout →": "చెక్అవుట్‌కు వెళ్లండి →",
"❌ Remove": "❌ తొలగించండి",
"Apply": "వర్తింపజేయండి",
"FREE": "ఉచితం"
},
"Tamil": {
"Shop by Category 🛍️": "வகை வாரியாக வாங்குங்கள் 🛍️",
"⚡ Flash Deals": "⚡ ஃபிளாஷ் டீல்ஸ்",
"🔥 Trending Picks": "🔥 டிரெண்டிங் தேர்வுகள்",
"✨ New Arrivals": "✨ புதிய வரவுகள்",
"⚡ LIMITED TIME DEALS": "⚡ குறுகிய கால சலுகைகள்",
"Save more on selected products today": "இன்று தேர்ந்தெடுத்த பொருட்களில் அதிகம் சேமியுங்கள்",
"Shop Deals →": "சலுகைகளைப் பாருங்கள் →",
"🎁 Get Extra ₹100 OFF": "🎁 கூடுதல் ₹100 தள்ளுபடி பெறுங்கள்",
"Use this coupon on your next purchase": "உங்கள் அடுத்த வாங்குதலில் இந்த கூப்பனைப் பயன்படுத்துங்கள்",
"Copy Code": "குறியீட்டை நகலெடுக்கவும்",
"Multiple Payments": "பல கட்டண முறைகள்",
"Choose your method": "உங்கள் முறையைத் தேர்ந்தெடுக்கவும்",
"Secure Shopping": "பாதுகாப்பான ஷாப்பிங்",
"Become a Seller →": "விற்பனையாளராகுங்கள் →",
"Grow your business and reach more customers.": "உங்கள் வணிகத்தை வளர்த்து அதிக வாடிக்கையாளர்களை அடையுங்கள்.",
"View Product →": "பொருளைப் பார்க்கவும் →",
"No products found": "பொருட்கள் எதுவும் இல்லை",
"Filters": "வடிகட்டிகள்",
"Price": "விலை",
"Under ₹1,000": "₹1,000-க்கு குறைவு",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "பிரபலமானவை",
"Price: Low to High": "விலை: குறைவு முதல் அதிகம்",
"Price: High to Low": "விலை: அதிகம் முதல் குறைவு",
"☰ All Categories": "☰ அனைத்து வகைகள்",
"🛒 Add to Cart": "🛒 கார்ட்டில் சேர்",
"⚡ Buy Now": "⚡ இப்போதே வாங்கு",
"✓ In Stock": "✓ இருப்பில் உள்ளது",
"✕ Out of Stock": "✕ இருப்பு இல்லை",
"Product Description": "பொருள் விளக்கம்",
"Specifications": "விவரக்குறிப்புகள்",
"Your cart is empty 🛒": "உங்கள் கார்ட் காலியாக உள்ளது 🛒",
"Continue Shopping": "ஷாப்பிங்கைத் தொடரவும்",
"Price Details": "விலை விவரங்கள்",
"Total": "மொத்தம்",
"Proceed to Checkout →": "செக்அவுட்டுக்குச் செல்லவும் →",
"❌ Remove": "❌ நீக்கு",
"Apply": "பயன்படுத்து",
"FREE": "இலவசம்"
},
"Gujarati": {
"Shop by Category 🛍️": "શ્રેણી મુજબ ખરીદો 🛍️",
"⚡ Flash Deals": "⚡ ફ્લેશ ડીલ્સ",
"🔥 Trending Picks": "🔥 ટ્રેન્ડિંગ પસંદગી",
"✨ New Arrivals": "✨ નવા આગમન",
"⚡ LIMITED TIME DEALS": "⚡ મર્યાદિત સમયની ઑફર્સ",
"Save more on selected products today": "આજે પસંદ કરેલા પ્રોડક્ટ્સ પર વધુ બચત કરો",
"Shop Deals →": "ઑફર્સ જુઓ →",
"🎁 Get Extra ₹100 OFF": "🎁 વધારાની ₹100 છૂટ મેળવો",
"Use this coupon on your next purchase": "તમારી આગામી ખરીદી પર આ કૂપન વાપરો",
"Copy Code": "કોડ કૉપી કરો",
"Multiple Payments": "અનેક ચુકવણી વિકલ્પો",
"Choose your method": "તમારી રીત પસંદ કરો",
"Secure Shopping": "સુરક્ષિત શોપિંગ",
"Become a Seller →": "વિક્રેતા બનો →",
"Grow your business and reach more customers.": "તમારો બિઝનેસ વધારો અને વધુ ગ્રાહકો સુધી પહોંચો.",
"View Product →": "પ્રોડક્ટ જુઓ →",
"No products found": "કોઈ પ્રોડક્ટ મળ્યું નથી",
"Filters": "ફિલ્ટર્સ",
"Price": "કિંમત",
"Under ₹1,000": "₹1,000 થી ઓછી",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "લોકપ્રિય",
"Price: Low to High": "કિંમત: ઓછીથી વધુ",
"Price: High to Low": "કિંમત: વધુથી ઓછી",
"☰ All Categories": "☰ બધી શ્રેણીઓ",
"🛒 Add to Cart": "🛒 કાર્ટમાં ઉમેરો",
"⚡ Buy Now": "⚡ હમણાં ખરીદો",
"✓ In Stock": "✓ સ્ટોકમાં છે",
"✕ Out of Stock": "✕ સ્ટોક નથી",
"Product Description": "પ્રોડક્ટ વર્ણન",
"Specifications": "વિશિષ્ટતાઓ",
"Your cart is empty 🛒": "તમારી કાર્ટ ખાલી છે 🛒",
"Continue Shopping": "ખરીદી ચાલુ રાખો",
"Price Details": "કિંમતની વિગતો",
"Total": "કુલ",
"Proceed to Checkout →": "ચેકઆઉટ પર જાઓ →",
"❌ Remove": "❌ દૂર કરો",
"Apply": "લાગુ કરો",
"FREE": "મફત"
},
"Kannada": {
"Shop by Category 🛍️": "ವರ್ಗದ ಪ್ರಕಾರ ಖರೀದಿಸಿ 🛍️",
"⚡ Flash Deals": "⚡ ಫ್ಲ್ಯಾಶ್ ಡೀಲ್ಸ್",
"🔥 Trending Picks": "🔥 ಟ್ರೆಂಡಿಂಗ್ ಆಯ್ಕೆಗಳು",
"✨ New Arrivals": "✨ ಹೊಸ ಆಗಮನ",
"⚡ LIMITED TIME DEALS": "⚡ ಸೀಮಿತ ಅವಧಿಯ ಆಫರ್‌ಗಳು",
"Save more on selected products today": "ಇಂದು ಆಯ್ದ ಉತ್ಪನ್ನಗಳ ಮೇಲೆ ಹೆಚ್ಚು ಉಳಿಸಿ",
"Shop Deals →": "ಆಫರ್‌ಗಳನ್ನು ನೋಡಿ →",
"🎁 Get Extra ₹100 OFF": "🎁 ಹೆಚ್ಚುವರಿ ₹100 ರಿಯಾಯಿತಿ ಪಡೆಯಿರಿ",
"Use this coupon on your next purchase": "ನಿಮ್ಮ ಮುಂದಿನ ಖರೀದಿಯಲ್ಲಿ ಈ ಕೂಪನ್ ಬಳಸಿ",
"Copy Code": "ಕೋಡ್ ನಕಲಿಸಿ",
"Multiple Payments": "ಹಲವು ಪಾವತಿ ವಿಧಾನಗಳು",
"Choose your method": "ನಿಮ್ಮ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ",
"Secure Shopping": "ಸುರಕ್ಷಿತ ಶಾಪಿಂಗ್",
"Become a Seller →": "ಮಾರಾಟಗಾರರಾಗಿ →",
"Grow your business and reach more customers.": "ನಿಮ್ಮ ವ್ಯಾಪಾರ ಬೆಳೆಸಿ, ಹೆಚ್ಚಿನ ಗ್ರಾಹಕರನ್ನು ತಲುಪಿ.",
"View Product →": "ಉತ್ಪನ್ನ ನೋಡಿ →",
"No products found": "ಯಾವುದೇ ಉತ್ಪನ್ನ ಸಿಗಲಿಲ್ಲ",
"Filters": "ಫಿಲ್ಟರ್‌ಗಳು",
"Price": "ಬೆಲೆ",
"Under ₹1,000": "₹1,000 ಕ್ಕಿಂತ ಕಡಿಮೆ",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "ಜನಪ್ರಿಯ",
"Price: Low to High": "ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚು",
"Price: High to Low": "ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ",
"☰ All Categories": "☰ ಎಲ್ಲಾ ವರ್ಗಗಳು",
"🛒 Add to Cart": "🛒 ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
"⚡ Buy Now": "⚡ ಈಗಲೇ ಖರೀದಿಸಿ",
"✓ In Stock": "✓ ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
"✕ Out of Stock": "✕ ಸ್ಟಾಕ್ ಇಲ್ಲ",
"Product Description": "ಉತ್ಪನ್ನದ ವಿವರಣೆ",
"Specifications": "ವಿಶೇಷಣಗಳು",
"Your cart is empty 🛒": "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ 🛒",
"Continue Shopping": "ಖರೀದಿ ಮುಂದುವರಿಸಿ",
"Price Details": "ಬೆಲೆ ವಿವರಗಳು",
"Total": "ಒಟ್ಟು",
"Proceed to Checkout →": "ಚೆಕ್‌ಔಟ್‌ಗೆ ಹೋಗಿ →",
"❌ Remove": "❌ ತೆಗೆದುಹಾಕಿ",
"Apply": "ಅನ್ವಯಿಸಿ",
"FREE": "ಉಚಿತ"
},
"Malayalam": {
"Shop by Category 🛍️": "വിഭാഗം അനുസരിച്ച് വാങ്ങുക 🛍️",
"⚡ Flash Deals": "⚡ ഫ്ലാഷ് ഡീൽസ്",
"🔥 Trending Picks": "🔥 ട്രെൻഡിംഗ് പിക്കുകൾ",
"✨ New Arrivals": "✨ പുതിയ വരവുകൾ",
"⚡ LIMITED TIME DEALS": "⚡ പരിമിത സമയ ഓഫറുകൾ",
"Save more on selected products today": "ഇന്ന് തിരഞ്ഞെടുത്ത ഉൽപ്പന്നങ്ങളിൽ കൂടുതൽ ലാഭിക്കൂ",
"Shop Deals →": "ഓഫറുകൾ കാണുക →",
"🎁 Get Extra ₹100 OFF": "🎁 അധിക ₹100 ഇളവ് നേടൂ",
"Use this coupon on your next purchase": "അടുത്ത വാങ്ങലിൽ ഈ കൂപ്പൺ ഉപയോഗിക്കൂ",
"Copy Code": "കോഡ് പകർത്തുക",
"Multiple Payments": "ഒന്നിലധികം പേയ്‌മെന്റ് രീതികൾ",
"Choose your method": "നിങ്ങളുടെ രീതി തിരഞ്ഞെടുക്കൂ",
"Secure Shopping": "സുരക്ഷിത ഷോപ്പിംഗ്",
"Become a Seller →": "വിൽപ്പനക്കാരനാകൂ →",
"Grow your business and reach more customers.": "നിങ്ങളുടെ ബിസിനസ് വളർത്തൂ, കൂടുതൽ ഉപഭോക്താക്കളിലെത്തൂ.",
"View Product →": "ഉൽപ്പന്നം കാണുക →",
"No products found": "ഉൽപ്പന്നങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
"Filters": "ഫിൽട്ടറുകൾ",
"Price": "വില",
"Under ₹1,000": "₹1,000-ൽ താഴെ",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "ജനപ്രിയം",
"Price: Low to High": "വില: കുറഞ്ഞത് മുതൽ കൂടിയത്",
"Price: High to Low": "വില: കൂടിയത് മുതൽ കുറഞ്ഞത്",
"☰ All Categories": "☰ എല്ലാ വിഭാഗങ്ങളും",
"🛒 Add to Cart": "🛒 കാർട്ടിൽ ചേർക്കുക",
"⚡ Buy Now": "⚡ ഇപ്പോൾ വാങ്ങുക",
"✓ In Stock": "✓ സ്റ്റോക്കുണ്ട്",
"✕ Out of Stock": "✕ സ്റ്റോക്കില്ല",
"Product Description": "ഉൽപ്പന്ന വിവരണം",
"Specifications": "സവിശേഷതകൾ",
"Your cart is empty 🛒": "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ് 🛒",
"Continue Shopping": "ഷോപ്പിംഗ് തുടരുക",
"Price Details": "വില വിവരങ്ങൾ",
"Total": "ആകെ",
"Proceed to Checkout →": "ചെക്ക്ഔട്ടിലേക്ക് പോകുക →",
"❌ Remove": "❌ നീക്കം ചെയ്യുക",
"Apply": "പ്രയോഗിക്കുക",
"FREE": "സൗജന്യം"
},
"Punjabi": {
"Shop by Category 🛍️": "ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਖਰੀਦੋ 🛍️",
"⚡ Flash Deals": "⚡ ਫਲੈਸ਼ ਡੀਲਜ਼",
"🔥 Trending Picks": "🔥 ਟਰੈਂਡਿੰਗ ਪਸੰਦ",
"✨ New Arrivals": "✨ ਨਵੇਂ ਆਗਮਨ",
"⚡ LIMITED TIME DEALS": "⚡ ਸੀਮਤ ਸਮੇਂ ਦੀਆਂ ਆਫ਼ਰਾਂ",
"Save more on selected products today": "ਅੱਜ ਚੁਣੇ ਉਤਪਾਦਾਂ 'ਤੇ ਹੋਰ ਬਚਤ ਕਰੋ",
"Shop Deals →": "ਆਫ਼ਰ ਵੇਖੋ →",
"🎁 Get Extra ₹100 OFF": "🎁 ₹100 ਵਾਧੂ ਛੂਟ ਪਾਓ",
"Use this coupon on your next purchase": "ਆਪਣੀ ਅਗਲੀ ਖਰੀਦ 'ਤੇ ਇਹ ਕੂਪਨ ਵਰਤੋ",
"Copy Code": "ਕੋਡ ਕਾਪੀ ਕਰੋ",
"Multiple Payments": "ਕਈ ਭੁਗਤਾਨ ਵਿਕਲਪ",
"Choose your method": "ਆਪਣਾ ਤਰੀਕਾ ਚੁਣੋ",
"Secure Shopping": "ਸੁਰੱਖਿਅਤ ਸ਼ਾਪਿੰਗ",
"Become a Seller →": "ਵਿਕਰੇਤਾ ਬਣੋ →",
"Grow your business and reach more customers.": "ਆਪਣਾ ਕਾਰੋਬਾਰ ਵਧਾਓ ਅਤੇ ਹੋਰ ਗਾਹਕਾਂ ਤੱਕ ਪਹੁੰਚੋ।",
"View Product →": "ਉਤਪਾਦ ਵੇਖੋ →",
"No products found": "ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ ਮਿਲਿਆ",
"Filters": "ਫਿਲਟਰ",
"Price": "ਕੀਮਤ",
"Under ₹1,000": "₹1,000 ਤੋਂ ਘੱਟ",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "ਮਸ਼ਹੂਰ",
"Price: Low to High": "ਕੀਮਤ: ਘੱਟ ਤੋਂ ਵੱਧ",
"Price: High to Low": "ਕੀਮਤ: ਵੱਧ ਤੋਂ ਘੱਟ",
"☰ All Categories": "☰ ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ",
"🛒 Add to Cart": "🛒 ਕਾਰਟ ਵਿੱਚ ਪਾਓ",
"⚡ Buy Now": "⚡ ਹੁਣੇ ਖਰੀਦੋ",
"✓ In Stock": "✓ ਸਟਾਕ ਵਿੱਚ ਹੈ",
"✕ Out of Stock": "✕ ਸਟਾਕ ਖਤਮ",
"Product Description": "ਉਤਪਾਦ ਦਾ ਵੇਰਵਾ",
"Specifications": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
"Your cart is empty 🛒": "ਤੁਹਾਡੀ ਕਾਰਟ ਖਾਲੀ ਹੈ 🛒",
"Continue Shopping": "ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ",
"Price Details": "ਕੀਮਤ ਦਾ ਵੇਰਵਾ",
"Total": "ਕੁੱਲ",
"Proceed to Checkout →": "ਚੈਕਆਉਟ 'ਤੇ ਜਾਓ →",
"❌ Remove": "❌ ਹਟਾਓ",
"Apply": "ਲਾਗੂ ਕਰੋ",
"FREE": "ਮੁਫ਼ਤ"
},
"Urdu": {
"Shop by Category 🛍️": "زمرے کے مطابق خریدیں 🛍️",
"⚡ Flash Deals": "⚡ فلیش ڈیلز",
"🔥 Trending Picks": "🔥 ٹرینڈنگ پکس",
"✨ New Arrivals": "✨ نئی آمد",
"⚡ LIMITED TIME DEALS": "⚡ محدود وقت کی آفرز",
"Save more on selected products today": "آج منتخب مصنوعات پر مزید بچت کریں",
"Shop Deals →": "آفرز دیکھیں →",
"🎁 Get Extra ₹100 OFF": "🎁 اضافی ₹100 کی رعایت حاصل کریں",
"Use this coupon on your next purchase": "اپنی اگلی خریداری پر یہ کوپن استعمال کریں",
"Copy Code": "کوڈ کاپی کریں",
"Multiple Payments": "متعدد ادائیگی کے طریقے",
"Choose your method": "اپنا طریقہ منتخب کریں",
"Secure Shopping": "محفوظ خریداری",
"Become a Seller →": "سیلر بنیں →",
"Grow your business and reach more customers.": "اپنا کاروبار بڑھائیں اور مزید گاہکوں تک پہنچیں۔",
"View Product →": "پروڈکٹ دیکھیں →",
"No products found": "کوئی پروڈکٹ نہیں ملا",
"Filters": "فلٹرز",
"Price": "قیمت",
"Under ₹1,000": "₹1,000 سے کم",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "مقبول",
"Price: Low to High": "قیمت: کم سے زیادہ",
"Price: High to Low": "قیمت: زیادہ سے کم",
"☰ All Categories": "☰ تمام زمرے",
"🛒 Add to Cart": "🛒 کارٹ میں شامل کریں",
"⚡ Buy Now": "⚡ ابھی خریدیں",
"✓ In Stock": "✓ اسٹاک میں ہے",
"✕ Out of Stock": "✕ اسٹاک ختم",
"Product Description": "پروڈکٹ کی تفصیل",
"Specifications": "خصوصیات",
"Your cart is empty 🛒": "آپ کا کارٹ خالی ہے 🛒",
"Continue Shopping": "خریداری جاری رکھیں",
"Price Details": "قیمت کی تفصیل",
"Total": "کل",
"Proceed to Checkout →": "چیک آؤٹ پر جائیں →",
"❌ Remove": "❌ ہٹائیں",
"Apply": "لاگو کریں",
"FREE": "مفت"
},
"Odia": {
"Shop by Category 🛍️": "ବର୍ଗ ଅନୁଯାୟୀ କିଣନ୍ତୁ 🛍️",
"⚡ Flash Deals": "⚡ ଫ୍ଲାସ୍ ଡିଲ୍ସ",
"🔥 Trending Picks": "🔥 ଟ୍ରେଣ୍ଡିଂ ପିକ୍ସ",
"✨ New Arrivals": "✨ ନୂଆ ଆଗମନ",
"⚡ LIMITED TIME DEALS": "⚡ ସୀମିତ ସମୟର ଅଫର୍",
"Save more on selected products today": "ଆଜି ବଛା ଉତ୍ପାଦ ଉପରେ ଅଧିକ ସଞ୍ଚୟ କରନ୍ତୁ",
"Shop Deals →": "ଅଫର୍ ଦେଖନ୍ତୁ →",
"🎁 Get Extra ₹100 OFF": "🎁 ଅତିରିକ୍ତ ₹100 ଛାଡ଼ ପାଆନ୍ତୁ",
"Use this coupon on your next purchase": "ଆପଣଙ୍କ ପରବର୍ତ୍ତୀ କିଣାରେ ଏହି କୁପନ୍ ବ୍ୟବହାର କରନ୍ତୁ",
"Copy Code": "କୋଡ୍ କପି କରନ୍ତୁ",
"Multiple Payments": "ଏକାଧିକ ପେମେଣ୍ଟ ବିକଳ୍ପ",
"Choose your method": "ଆପଣଙ୍କ ପଦ୍ଧତି ବାଛନ୍ତୁ",
"Secure Shopping": "ସୁରକ୍ଷିତ ସପିଂ",
"Become a Seller →": "ବିକ୍ରେତା ହୁଅନ୍ତୁ →",
"Grow your business and reach more customers.": "ଆପଣଙ୍କ ବ୍ୟବସାୟ ବଢ଼ାନ୍ତୁ ଏବଂ ଅଧିକ ଗ୍ରାହକଙ୍କ ପାଖରେ ପହଞ୍ଚନ୍ତୁ।",
"View Product →": "ଉତ୍ପାଦ ଦେଖନ୍ତୁ →",
"No products found": "କୌଣସି ଉତ୍ପାଦ ମିଳିଲା ନାହିଁ",
"Filters": "ଫିଲ୍ଟର୍",
"Price": "ମୂଲ୍ୟ",
"Under ₹1,000": "₹1,000 ରୁ କମ୍",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "ଲୋକପ୍ରିୟ",
"Price: Low to High": "ମୂଲ୍ୟ: କମ୍ ରୁ ଅଧିକ",
"Price: High to Low": "ମୂଲ୍ୟ: ଅଧିକ ରୁ କମ୍",
"☰ All Categories": "☰ ସମସ୍ତ ବର୍ଗ",
"🛒 Add to Cart": "🛒 କାର୍ଟରେ ଯୋଡ଼ନ୍ତୁ",
"⚡ Buy Now": "⚡ ବର୍ତ୍ତମାନ କିଣନ୍ତୁ",
"✓ In Stock": "✓ ଷ୍ଟକ୍ ରେ ଅଛି",
"✕ Out of Stock": "✕ ଷ୍ଟକ୍ ନାହିଁ",
"Product Description": "ଉତ୍ପାଦ ବିବରଣୀ",
"Specifications": "ବିଶେଷତା",
"Your cart is empty 🛒": "ଆପଣଙ୍କ କାର୍ଟ ଖାଲି ଅଛି 🛒",
"Continue Shopping": "କିଣାକିଣି ଜାରି ରଖନ୍ତୁ",
"Price Details": "ମୂଲ୍ୟ ବିବରଣୀ",
"Total": "ମୋଟ",
"Proceed to Checkout →": "ଚେକଆଉଟ୍ କୁ ଯାଆନ୍ତୁ →",
"❌ Remove": "❌ ହଟାନ୍ତୁ",
"Apply": "ପ୍ରୟୋଗ କରନ୍ତୁ",
"FREE": "ମାଗଣା"
},
"Assamese": {
"Shop by Category 🛍️": "শ্ৰেণী অনুসৰি কিনক 🛍️",
"⚡ Flash Deals": "⚡ ফ্লেছ ডিল",
"🔥 Trending Picks": "🔥 ট্ৰেণ্ডিং পিক",
"✨ New Arrivals": "✨ নতুন আগমন",
"⚡ LIMITED TIME DEALS": "⚡ সীমিত সময়ৰ অফাৰ",
"Save more on selected products today": "আজি বাছনি কৰা সামগ্ৰীত অধিক সঞ্চয় কৰক",
"Shop Deals →": "অফাৰ চাওক →",
"🎁 Get Extra ₹100 OFF": "🎁 অতিৰিক্ত ₹100 ৰেহাই লাভ কৰক",
"Use this coupon on your next purchase": "আপোনাৰ পাছৰ কিনাত এই কুপন ব্যৱহাৰ কৰক",
"Copy Code": "কোড কপি কৰক",
"Multiple Payments": "একাধিক পেমেণ্ট",
"Choose your method": "আপোনাৰ পদ্ধতি বাছক",
"Secure Shopping": "সুৰক্ষিত শ্বপিং",
"Become a Seller →": "বিক্ৰেতা হওক →",
"Grow your business and reach more customers.": "আপোনাৰ ব্যৱসায় বঢ়াওক আৰু অধিক গ্ৰাহকৰ ওচৰ পাওক।",
"View Product →": "সামগ্ৰী চাওক →",
"No products found": "কোনো সামগ্ৰী পোৱা নগ'ল",
"Filters": "ফিল্টাৰ",
"Price": "দাম",
"Under ₹1,000": "₹1,000তকৈ কম",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000+",
"Popular": "জনপ্ৰিয়",
"Price: Low to High": "দাম: কমৰ পৰা বেছি",
"Price: High to Low": "দাম: বেছিৰ পৰা কম",
"☰ All Categories": "☰ সকলো শ্ৰেণী",
"🛒 Add to Cart": "🛒 কাৰ্টত যোগ কৰক",
"⚡ Buy Now": "⚡ এতিয়াই কিনক",
"✓ In Stock": "✓ ষ্টকত আছে",
"✕ Out of Stock": "✕ ষ্টক নাই",
"Product Description": "সামগ্ৰীৰ বিৱৰণ",
"Specifications": "বিশেষত্ব",
"Your cart is empty 🛒": "আপোনাৰ কাৰ্ট খালী 🛒",
"Continue Shopping": "কিনা-কটা অব্যাহত ৰাখক",
"Price Details": "দামৰ বিৱৰণ",
"Total": "মুঠ",
"Proceed to Checkout →": "চেকআউটলৈ যাওক →",
"❌ Remove": "❌ আঁতৰাওক",
"Apply": "প্ৰয়োগ কৰক",
"FREE": "বিনামূলীয়া"
},
"French": {
"Shop by Category 🛍️": "Acheter par catégorie 🛍️",
"⚡ Flash Deals": "⚡ Ventes flash",
"🔥 Trending Picks": "🔥 Tendances",
"✨ New Arrivals": "✨ Nouveautés",
"⚡ LIMITED TIME DEALS": "⚡ OFFRES À DURÉE LIMITÉE",
"Save more on selected products today": "Économisez plus aujourd'hui sur une sélection de produits",
"Shop Deals →": "Voir les offres →",
"🎁 Get Extra ₹100 OFF": "🎁 Obtenez ₹100 de réduction en plus",
"Use this coupon on your next purchase": "Utilisez ce coupon pour votre prochain achat",
"Copy Code": "Copier le code",
"Multiple Payments": "Paiements multiples",
"Choose your method": "Choisissez votre méthode",
"Secure Shopping": "Achats sécurisés",
"Become a Seller →": "Devenir vendeur →",
"Grow your business and reach more customers.": "Développez votre activité et touchez plus de clients.",
"View Product →": "Voir le produit →",
"No products found": "Aucun produit trouvé",
"Filters": "Filtres",
"Price": "Prix",
"Under ₹1,000": "Moins de ₹1 000",
"₹1,000–₹5,000": "₹1 000–₹5 000",
"₹5,000+": "Plus de ₹5 000",
"Popular": "Populaires",
"Price: Low to High": "Prix : croissant",
"Price: High to Low": "Prix : décroissant",
"☰ All Categories": "☰ Toutes les catégories",
"🛒 Add to Cart": "🛒 Ajouter au panier",
"⚡ Buy Now": "⚡ Acheter maintenant",
"✓ In Stock": "✓ En stock",
"✕ Out of Stock": "✕ Rupture de stock",
"Product Description": "Description du produit",
"Specifications": "Caractéristiques",
"Your cart is empty 🛒": "Votre panier est vide 🛒",
"Continue Shopping": "Continuer vos achats",
"Price Details": "Détails du prix",
"Total": "Total",
"Proceed to Checkout →": "Passer à la caisse →",
"❌ Remove": "❌ Supprimer",
"Apply": "Appliquer",
"FREE": "GRATUIT"
},
"German": {
"Shop by Category 🛍️": "Nach Kategorie einkaufen 🛍️",
"⚡ Flash Deals": "⚡ Blitzangebote",
"🔥 Trending Picks": "🔥 Im Trend",
"✨ New Arrivals": "✨ Neuheiten",
"⚡ LIMITED TIME DEALS": "⚡ ZEITLICH BEGRENZTE ANGEBOTE",
"Save more on selected products today": "Heute bei ausgewählten Produkten mehr sparen",
"Shop Deals →": "Angebote ansehen →",
"🎁 Get Extra ₹100 OFF": "🎁 Zusätzlich ₹100 Rabatt erhalten",
"Use this coupon on your next purchase": "Nutzen Sie diesen Gutschein bei Ihrem nächsten Einkauf",
"Copy Code": "Code kopieren",
"Multiple Payments": "Mehrere Zahlungsarten",
"Choose your method": "Wählen Sie Ihre Methode",
"Secure Shopping": "Sicher einkaufen",
"Become a Seller →": "Verkäufer werden →",
"Grow your business and reach more customers.": "Bauen Sie Ihr Geschäft aus und erreichen Sie mehr Kunden.",
"View Product →": "Produkt ansehen →",
"No products found": "Keine Produkte gefunden",
"Filters": "Filter",
"Price": "Preis",
"Under ₹1,000": "Unter ₹1.000",
"₹1,000–₹5,000": "₹1.000–₹5.000",
"₹5,000+": "Über ₹5.000",
"Popular": "Beliebt",
"Price: Low to High": "Preis: aufsteigend",
"Price: High to Low": "Preis: absteigend",
"☰ All Categories": "☰ Alle Kategorien",
"🛒 Add to Cart": "🛒 In den Warenkorb",
"⚡ Buy Now": "⚡ Jetzt kaufen",
"✓ In Stock": "✓ Auf Lager",
"✕ Out of Stock": "✕ Nicht auf Lager",
"Product Description": "Produktbeschreibung",
"Specifications": "Spezifikationen",
"Your cart is empty 🛒": "Ihr Warenkorb ist leer 🛒",
"Continue Shopping": "Weiter einkaufen",
"Price Details": "Preisdetails",
"Total": "Gesamt",
"Proceed to Checkout →": "Zur Kasse →",
"❌ Remove": "❌ Entfernen",
"Apply": "Anwenden",
"FREE": "GRATIS"
},
"Spanish": {
"Shop by Category 🛍️": "Comprar por categoría 🛍️",
"⚡ Flash Deals": "⚡ Ofertas flash",
"🔥 Trending Picks": "🔥 Tendencias",
"✨ New Arrivals": "✨ Novedades",
"⚡ LIMITED TIME DEALS": "⚡ OFERTAS POR TIEMPO LIMITADO",
"Save more on selected products today": "Ahorra más hoy en productos seleccionados",
"Shop Deals →": "Ver ofertas →",
"🎁 Get Extra ₹100 OFF": "🎁 Obtén ₹100 de descuento extra",
"Use this coupon on your next purchase": "Usa este cupón en tu próxima compra",
"Copy Code": "Copiar código",
"Multiple Payments": "Múltiples métodos de pago",
"Choose your method": "Elige tu método",
"Secure Shopping": "Compra segura",
"Become a Seller →": "Hazte vendedor →",
"Grow your business and reach more customers.": "Haz crecer tu negocio y llega a más clientes.",
"View Product →": "Ver producto →",
"No products found": "No se encontraron productos",
"Filters": "Filtros",
"Price": "Precio",
"Under ₹1,000": "Menos de ₹1,000",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "Más de ₹5,000",
"Popular": "Popular",
"Price: Low to High": "Precio: de menor a mayor",
"Price: High to Low": "Precio: de mayor a menor",
"☰ All Categories": "☰ Todas las categorías",
"🛒 Add to Cart": "🛒 Añadir al carrito",
"⚡ Buy Now": "⚡ Comprar ahora",
"✓ In Stock": "✓ En stock",
"✕ Out of Stock": "✕ Agotado",
"Product Description": "Descripción del producto",
"Specifications": "Especificaciones",
"Your cart is empty 🛒": "Tu carrito está vacío 🛒",
"Continue Shopping": "Seguir comprando",
"Price Details": "Detalles del precio",
"Total": "Total",
"Proceed to Checkout →": "Ir al pago →",
"❌ Remove": "❌ Eliminar",
"Apply": "Aplicar",
"FREE": "GRATIS"
},
"Italian": {
"Shop by Category 🛍️": "Acquista per categoria 🛍️",
"⚡ Flash Deals": "⚡ Offerte lampo",
"🔥 Trending Picks": "🔥 Di tendenza",
"✨ New Arrivals": "✨ Novità",
"⚡ LIMITED TIME DEALS": "⚡ OFFERTE A TEMPO LIMITATO",
"Save more on selected products today": "Risparmia di più oggi su prodotti selezionati",
"Shop Deals →": "Vedi offerte →",
"🎁 Get Extra ₹100 OFF": "🎁 Ottieni ₹100 di sconto extra",
"Use this coupon on your next purchase": "Usa questo coupon al tuo prossimo acquisto",
"Copy Code": "Copia codice",
"Multiple Payments": "Pagamenti multipli",
"Choose your method": "Scegli il tuo metodo",
"Secure Shopping": "Acquisti sicuri",
"Become a Seller →": "Diventa venditore →",
"Grow your business and reach more customers.": "Fai crescere la tua attività e raggiungi più clienti.",
"View Product →": "Vedi prodotto →",
"No products found": "Nessun prodotto trovato",
"Filters": "Filtri",
"Price": "Prezzo",
"Under ₹1,000": "Meno di ₹1.000",
"₹1,000–₹5,000": "₹1.000–₹5.000",
"₹5,000+": "Più di ₹5.000",
"Popular": "Popolari",
"Price: Low to High": "Prezzo: dal più basso",
"Price: High to Low": "Prezzo: dal più alto",
"☰ All Categories": "☰ Tutte le categorie",
"🛒 Add to Cart": "🛒 Aggiungi al carrello",
"⚡ Buy Now": "⚡ Acquista ora",
"✓ In Stock": "✓ Disponibile",
"✕ Out of Stock": "✕ Esaurito",
"Product Description": "Descrizione del prodotto",
"Specifications": "Specifiche",
"Your cart is empty 🛒": "Il tuo carrello è vuoto 🛒",
"Continue Shopping": "Continua lo shopping",
"Price Details": "Dettagli del prezzo",
"Total": "Totale",
"Proceed to Checkout →": "Vai al pagamento →",
"❌ Remove": "❌ Rimuovi",
"Apply": "Applica",
"FREE": "GRATIS"
},
"Japanese": {
"Shop by Category 🛍️": "カテゴリから探す 🛍️",
"⚡ Flash Deals": "⚡ フラッシュセール",
"🔥 Trending Picks": "🔥 注目の商品",
"✨ New Arrivals": "✨ 新着商品",
"⚡ LIMITED TIME DEALS": "⚡ 期間限定セール",
"Save more on selected products today": "本日は対象商品がさらにお得",
"Shop Deals →": "セールを見る →",
"🎁 Get Extra ₹100 OFF": "🎁 さらに₹100オフ",
"Use this coupon on your next purchase": "次回のご購入でこのクーポンをご利用ください",
"Copy Code": "コードをコピー",
"Multiple Payments": "複数のお支払い方法",
"Choose your method": "お支払い方法を選択",
"Secure Shopping": "安心のショッピング",
"Become a Seller →": "販売者になる →",
"Grow your business and reach more customers.": "ビジネスを成長させ、より多くのお客様にリーチしましょう。",
"View Product →": "商品を見る →",
"No products found": "商品が見つかりません",
"Filters": "絞り込み",
"Price": "価格",
"Under ₹1,000": "₹1,000未満",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000以上",
"Popular": "人気順",
"Price: Low to High": "価格の安い順",
"Price: High to Low": "価格の高い順",
"☰ All Categories": "☰ すべてのカテゴリ",
"🛒 Add to Cart": "🛒 カートに追加",
"⚡ Buy Now": "⚡ 今すぐ購入",
"✓ In Stock": "✓ 在庫あり",
"✕ Out of Stock": "✕ 在庫切れ",
"Product Description": "商品説明",
"Specifications": "仕様",
"Your cart is empty 🛒": "カートは空です 🛒",
"Continue Shopping": "買い物を続ける",
"Price Details": "価格の詳細",
"Total": "合計",
"Proceed to Checkout →": "レジに進む →",
"❌ Remove": "❌ 削除",
"Apply": "適用",
"FREE": "無料"
},
"Chinese": {
"Shop by Category 🛍️": "按分类选购 🛍️",
"⚡ Flash Deals": "⚡ 限时特惠",
"🔥 Trending Picks": "🔥 热门精选",
"✨ New Arrivals": "✨ 新品上架",
"⚡ LIMITED TIME DEALS": "⚡ 限时优惠",
"Save more on selected products today": "今日精选商品更多优惠",
"Shop Deals →": "查看优惠 →",
"🎁 Get Extra ₹100 OFF": "🎁 额外立减 ₹100",
"Use this coupon on your next purchase": "下次购物可使用此优惠券",
"Copy Code": "复制优惠码",
"Multiple Payments": "多种支付方式",
"Choose your method": "选择您的支付方式",
"Secure Shopping": "安全购物",
"Become a Seller →": "成为卖家 →",
"Grow your business and reach more customers.": "拓展您的业务，触达更多客户。",
"View Product →": "查看商品 →",
"No products found": "未找到商品",
"Filters": "筛选",
"Price": "价格",
"Under ₹1,000": "₹1,000 以下",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000 以上",
"Popular": "热门",
"Price: Low to High": "价格：从低到高",
"Price: High to Low": "价格：从高到低",
"☰ All Categories": "☰ 所有分类",
"🛒 Add to Cart": "🛒 加入购物车",
"⚡ Buy Now": "⚡ 立即购买",
"✓ In Stock": "✓ 有货",
"✕ Out of Stock": "✕ 缺货",
"Product Description": "商品描述",
"Specifications": "规格参数",
"Your cart is empty 🛒": "您的购物车是空的 🛒",
"Continue Shopping": "继续购物",
"Price Details": "价格明细",
"Total": "合计",
"Proceed to Checkout →": "去结算 →",
"❌ Remove": "❌ 删除",
"Apply": "应用",
"FREE": "免费"
},
"Korean": {
"Shop by Category 🛍️": "카테고리별 쇼핑 🛍️",
"⚡ Flash Deals": "⚡ 플래시 특가",
"🔥 Trending Picks": "🔥 인기 상품",
"✨ New Arrivals": "✨ 신상품",
"⚡ LIMITED TIME DEALS": "⚡ 한정 시간 특가",
"Save more on selected products today": "오늘 선택 상품 더 많이 절약하세요",
"Shop Deals →": "특가 보기 →",
"🎁 Get Extra ₹100 OFF": "🎁 ₹100 추가 할인 받기",
"Use this coupon on your next purchase": "다음 구매 시 이 쿠폰을 사용하세요",
"Copy Code": "코드 복사",
"Multiple Payments": "다양한 결제 수단",
"Choose your method": "결제 방법을 선택하세요",
"Secure Shopping": "안전한 쇼핑",
"Become a Seller →": "판매자 되기 →",
"Grow your business and reach more customers.": "사업을 성장시키고 더 많은 고객에게 다가가세요.",
"View Product →": "상품 보기 →",
"No products found": "상품을 찾을 수 없습니다",
"Filters": "필터",
"Price": "가격",
"Under ₹1,000": "₹1,000 미만",
"₹1,000–₹5,000": "₹1,000–₹5,000",
"₹5,000+": "₹5,000 이상",
"Popular": "인기순",
"Price: Low to High": "가격: 낮은 순",
"Price: High to Low": "가격: 높은 순",
"☰ All Categories": "☰ 모든 카테고리",
"🛒 Add to Cart": "🛒 장바구니에 담기",
"⚡ Buy Now": "⚡ 바로 구매",
"✓ In Stock": "✓ 재고 있음",
"✕ Out of Stock": "✕ 품절",
"Product Description": "상품 설명",
"Specifications": "사양",
"Your cart is empty 🛒": "장바구니가 비어 있습니다 🛒",
"Continue Shopping": "쇼핑 계속하기",
"Price Details": "가격 상세",
"Total": "합계",
"Proceed to Checkout →": "결제하기 →",
"❌ Remove": "❌ 삭제",
"Apply": "적용",
"FREE": "무료"
}
};

var PS_LANG_CODES = {Hindi:"hi",Bengali:"bn",Marathi:"mr",Telugu:"te",Tamil:"ta",Gujarati:"gu",Kannada:"kn",Malayalam:"ml",Punjabi:"pa",Urdu:"ur",Odia:"or",Assamese:"as",French:"fr",German:"de",Spanish:"es",Italian:"it",Japanese:"ja",Chinese:"zh",Korean:"ko"};

var PS_DICT_CACHE = {};

/* Test ke liye: koi bhi page ?lang=Hindi laga kar kholo (jaise index.html?lang=Hindi) */
(function(){
  try{
    var q = new URLSearchParams(location.search).get("lang");
    if(q && (q === "English" || PS_LANG_CODES[q])){ localStorage.setItem("psmart-language", q); }
    console.info("PS Mart translate-extra.js loaded. Language:", localStorage.getItem("psmart-language") || "English");
  }catch(e){}
})();

function psGetDict(lang){
  if(PS_DICT_CACHE[lang]) return PS_DICT_CACHE[lang];
  var base = (typeof PS_TRANSLATIONS !== "undefined" && PS_TRANSLATIONS[lang]) || {};
  var d = {};
  Object.keys(base).forEach(function(k){ d[k] = base[k]; });
  var ex = PS_EXTRA[lang] || {};
  Object.keys(ex).forEach(function(k){ d[k] = ex[k]; });
  PS_DICT_CACHE[lang] = d;
  return d;
}

function translatePage(){
  var lang = null;
  try{ lang = localStorage.getItem("psmart-language"); }catch(e){}
  if(!lang || lang === "English") return;

  var d = psGetDict(lang);
  if(!d || !Object.keys(d).length) return;

  var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode: function(n){
      var p = n.parentNode;
      if(!p || /^(SCRIPT|STYLE|TEXTAREA|NOSCRIPT)$/.test(p.nodeName)) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    }
  });
  var nodes = [], n;
  while((n = walker.nextNode())) nodes.push(n);

  nodes.forEach(function(t){
    var raw = t.nodeValue;
    if(!raw || !raw.trim()) return;
    var key = raw.trim();
    if(d[key]) t.nodeValue = raw.replace(key, d[key]);
  });

  document.querySelectorAll("input[placeholder], textarea[placeholder]").forEach(function(i){
    var o = i.getAttribute("placeholder");
    if(d[o]) i.setAttribute("placeholder", d[o]);
  });

  document.documentElement.lang = PS_LANG_CODES[lang] || "en";
}

document.addEventListener("DOMContentLoaded", function(){
  translatePage();
  var timer = null;
  new MutationObserver(function(){
    clearTimeout(timer);
    timer = setTimeout(translatePage, 120);
  }).observe(document.body, {childList:true, subtree:true});
});
